var e;e||(e=typeof Module !== 'undefined' ? Module : {});var g={},h;for(h in e)e.hasOwnProperty(h)&&(g[h]=e[h]);e.arguments=[];e.thisProgram="./this.program";e.quit=function(a,b){throw b;};e.preRun=[];e.postRun=[];var r=!1,t=!1,aa=!1,ba=!1,ca=!1;r="object"===typeof window;t="function"===typeof importScripts;aa=(ba="object"===typeof process&&"function"===typeof require)&&!r&&!t;ca=!r&&!aa&&!t;var u="";
if(aa){u=__dirname+"/";var da,ea;e.read=function(a,b){da||(da=require("fs"));ea||(ea=require("path"));a=ea.normalize(a);a=da.readFileSync(a);return b?a:a.toString()};e.readBinary=function(a){a=e.read(a,!0);a.buffer||(a=new Uint8Array(a));a.buffer||w("Assertion failed: undefined");return a};1<process.argv.length&&(e.thisProgram=process.argv[1].replace(/\\/g,"/"));e.arguments=process.argv.slice(2);"undefined"!==typeof module&&(module.exports=e);process.on("uncaughtException",function(a){if(!(a instanceof
x))throw a;});process.on("unhandledRejection",w);e.quit=function(a){process.exit(a)};e.inspect=function(){return"[Emscripten Module object]"}}else if(ca)"undefined"!=typeof read&&(e.read=function(a){return read(a)}),e.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");"object"===typeof a||w("Assertion failed: undefined");return a},"undefined"!=typeof scriptArgs?e.arguments=scriptArgs:"undefined"!=typeof arguments&&(e.arguments=arguments),
"function"===typeof quit&&(e.quit=function(a){quit(a)});else if(r||t)t?u=self.location.href:document.currentScript&&(u=document.currentScript.src),u=0!==u.indexOf("blob:")?u.substr(0,u.lastIndexOf("/")+1):"",e.read=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},t&&(e.readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),e.readAsync=function(a,b,c){var d=new XMLHttpRequest;
d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)},e.setWindowTitle=function(a){document.title=a};var fa=e.print||("undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null),y=e.printErr||("undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||fa);for(h in g)g.hasOwnProperty(h)&&(e[h]=g[h]);g=void 0;
var ha={"f64-rem":function(a,b){return a%b},"debugger":function(){debugger}};"object"!==typeof WebAssembly&&y("no native wasm support detected");var z,ia=!1,ja="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ka(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&ja)return ja.decode(a.subarray(b,c));for(d="";b<c;){var f=a[b++];if(f&128){var k=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|k);else{var l=a[b++]&63;f=224==(f&240)?(f&15)<<12|k<<6|l:(f&7)<<18|k<<12|l<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d}function A(a,b){return a?ka(B,a,b):""}
function C(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var k=0;k<a.length;++k){var l=a.charCodeAt(k);if(55296<=l&&57343>=l){var m=a.charCodeAt(++k);l=65536+((l&1023)<<10)|m&1023}if(127>=l){if(c>=d)break;b[c++]=l}else{if(2047>=l){if(c+1>=d)break;b[c++]=192|l>>6}else{if(65535>=l){if(c+2>=d)break;b[c++]=224|l>>12}else{if(c+3>=d)break;b[c++]=240|l>>18;b[c++]=128|l>>12&63}b[c++]=128|l>>6&63}b[c++]=128|l&63}}b[c]=0;return c-f}
function la(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function ma(a){var b=la(a)+1,c=na(b);C(a,D,c,b);return c}function oa(a){0<a%65536&&(a+=65536-a%65536);return a}var buffer,D,B,E,pa,F,qa,ra,G;
function sa(){e.HEAP8=D=new Int8Array(buffer);e.HEAP16=E=new Int16Array(buffer);e.HEAP32=F=new Int32Array(buffer);e.HEAPU8=B=new Uint8Array(buffer);e.HEAPU16=pa=new Uint16Array(buffer);e.HEAPU32=qa=new Uint32Array(buffer);e.HEAPF32=ra=new Float32Array(buffer);e.HEAPF64=G=new Float64Array(buffer)}var ta=e.TOTAL_MEMORY||33554432;5242880>ta&&y("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+ta+"! (TOTAL_STACK=5242880)");
e.buffer?buffer=e.buffer:"object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(z=new WebAssembly.Memory({initial:ta/65536}),buffer=z.buffer):buffer=new ArrayBuffer(ta);sa();F[137208]=5791744;function ua(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.lc;"number"===typeof c?void 0===b.Tb?e.dynCall_v(c):e.dynCall_vi(c,b.Tb):c(void 0===b.Tb?null:b.Tb)}}}var va=[],wa=[],xa=[],ya=[],za=[];function Aa(){var a=e.preRun.shift();va.unshift(a)}
var H=0,Ba=null,I=null;e.preloadedImages={};e.preloadedAudios={};function Ca(){var a=J;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var J="plmpeg-sapp.wasm";if(!Ca()){var Da=J;J=e.locateFile?e.locateFile(Da,u):u+Da}function Ea(){try{if(e.wasmBinary)return new Uint8Array(e.wasmBinary);if(e.readBinary)return e.readBinary(J);throw"both async and sync fetching of the wasm failed";}catch(a){w(a)}}
function Fa(){return e.wasmBinary||!r&&!t||"function"!==typeof fetch?new Promise(function(a){a(Ea())}):fetch(J,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+J+"'";return a.arrayBuffer()}).catch(function(){return Ea()})}
function Ha(a){function b(a){e.asm=a.exports;H--;e.monitorRunDependencies&&e.monitorRunDependencies(H);0==H&&(null!==Ba&&(clearInterval(Ba),Ba=null),I&&(a=I,I=null,a()))}function c(a){b(a.instance)}function d(a){return Fa().then(function(a){return WebAssembly.instantiate(a,f)}).then(a,function(a){y("failed to asynchronously prepare wasm: "+a);w(a)})}var f={env:a,global:{NaN:NaN,Infinity:Infinity},"global.Math":Math,asm2wasm:ha};H++;e.monitorRunDependencies&&e.monitorRunDependencies(H);if(e.instantiateWasm)try{return e.instantiateWasm(f,
b)}catch(k){return y("Module.instantiateWasm callback failed with error: "+k),!1}(function(){if(e.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||Ca()||"function"!==typeof fetch)return d(c);fetch(J,{credentials:"same-origin"}).then(function(a){return WebAssembly.instantiateStreaming(a,f).then(c,function(a){y("wasm streaming compile failed: "+a);y("falling back to ArrayBuffer instantiation");d(c)})})})();return{}}
e.asm=function(a,b){b.memory=z;b.table=new WebAssembly.Table({initial:51,maximum:51,element:"anyfunc"});b.__memory_base=1024;b.__table_base=0;return Ha(b)};var Ia=[null,[],[]],K=0;function L(){K+=4;return F[K-4>>2]}var Ja={},Ka=0,La=0,M=0,Ma=0,Na=0,Oa=null,Pa=null,Qa=!1;function Ra(){for(var a=N.length-1;0<=a;--a)Sa(a);N=[];Ta=[]}var Ta=[];function Ua(){if(Va&&Wa.Lb)for(var a=0;a<Ta.length;++a){var b=Ta[a];Ta.splice(a,1);--a;b.pc.apply(this,b.ic)}}var Va=0,Wa=null,N=[];
function Xa(){return-1!==navigator.userAgent.indexOf("MSIE")||0<navigator.appVersion.indexOf("Trident/")}function Sa(a){var b=N[a];b.target.removeEventListener(b.Jb,b.bc,b.Mb);N.splice(a,1)}function O(a){function b(b){++Va;Wa=a;Ua();a.Ob(b);Ua();--Va}if(a.Nb)a.bc=b,a.target.addEventListener(a.Jb,b,a.Mb),N.push(a),Qa||(ya.push(Ra),Qa=!0);else for(var c=0;c<N.length;++c)N[c].target==a.target&&N[c].Jb==a.Jb&&Sa(c--)}
var Ya=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function P(a){try{if(!a)return window;"number"===typeof a&&(a=Ya[a]||A(a));return"#window"===a?window:"#document"===a?document:"#screen"===a?screen:"#canvas"===a?e.canvas:"string"===typeof a?document.getElementById(a):a}catch(b){return null}}function Za(){return D.length}
function $a(a){"number"===typeof a&&(a=A(a));return a&&"#canvas"!==a?"undefined"!==typeof ab&&bb[a]?bb[a]:P(a):"undefined"!==typeof ab&&bb.canvas?bb.canvas:e.canvas}
function cb(a,b,c,d,f,k){Ka||(Ka=Q(164));a={target:P(a),Lb:Xa()?!1:!0,Jb:k,Nb:d,Ob:function(a){a=a||window.event;var c=Ka;C(a.key?a.key:"",B,c+0,32);C(a.code?a.code:"",B,c+32,32);F[c+64>>2]=a.location;F[c+68>>2]=a.ctrlKey;F[c+72>>2]=a.shiftKey;F[c+76>>2]=a.altKey;F[c+80>>2]=a.metaKey;F[c+84>>2]=a.repeat;C(a.locale?a.locale:"",B,c+88,32);C(a.char?a.char:"",B,c+120,32);F[c+152>>2]=a.charCode;F[c+156>>2]=a.keyCode;F[c+160>>2]=a.which;R(d,f,c,b)&&a.preventDefault()},Mb:c};O(a)}
function db(a,b,c){G[a>>3]=window.performance&&window.performance.now?window.performance.now():Date.now();F[a+8>>2]=b.screenX;F[a+12>>2]=b.screenY;F[a+16>>2]=b.clientX;F[a+20>>2]=b.clientY;F[a+24>>2]=b.ctrlKey;F[a+28>>2]=b.shiftKey;F[a+32>>2]=b.altKey;F[a+36>>2]=b.metaKey;E[a+40>>1]=b.button;E[a+42>>1]=b.buttons;F[a+44>>2]=b.movementX||b.mozMovementX||b.webkitMovementX||b.screenX-Oa;F[a+48>>2]=b.movementY||b.mozMovementY||b.webkitMovementY||b.screenY-Pa;if(e.canvas){var d=e.canvas.getBoundingClientRect();
F[a+60>>2]=b.clientX-d.left;F[a+64>>2]=b.clientY-d.top}else F[a+60>>2]=0,F[a+64>>2]=0;c?(d=c.getBoundingClientRect?c.getBoundingClientRect():{left:0,top:0},F[a+52>>2]=b.clientX-d.left,F[a+56>>2]=b.clientY-d.top):(F[a+52>>2]=0,F[a+56>>2]=0);"wheel"!==b.type&&"mousewheel"!==b.type&&(Oa=b.screenX,Pa=b.screenY)}
function S(a,b,c,d,f,k){La||(La=Q(72));a=P(a);c={target:a,Lb:"mousemove"!=k&&"mouseenter"!=k&&"mouseleave"!=k,Jb:k,Nb:d,Ob:function(c){c=c||window.event;db(La,c,a);R(d,f,La,b)&&c.preventDefault()},Mb:c};Xa()&&"mousedown"==k&&(c.Lb=!1);O(c)}
function eb(a,b,c,d){Ma||(Ma=Q(36));a=P(a);O({target:a,Lb:!1,Jb:"resize",Nb:d,Ob:function(c){c=c||window.event;if(c.target==a){var f=0<window.pageXOffset||0<window.pageYOffset?[window.pageXOffset,window.pageYOffset]:"undefined"!==typeof document.documentElement.scrollLeft||"undefined"!==typeof document.documentElement.scrollTop?[document.documentElement.scrollLeft,document.documentElement.scrollTop]:[document.body.scrollLeft|0,document.body.scrollTop|0],l=Ma;F[l>>2]=c.detail;F[l+4>>2]=document.body.clientWidth;
F[l+8>>2]=document.body.clientHeight;F[l+12>>2]=window.innerWidth;F[l+16>>2]=window.innerHeight;F[l+20>>2]=window.outerWidth;F[l+24>>2]=window.outerHeight;F[l+28>>2]=f[0];F[l+32>>2]=f[1];R(d,10,l,b)&&c.preventDefault()}},Mb:c})}
function fb(a,b,c,d,f,k){Na||(Na=Q(1684));a=P(a);O({target:a,Lb:"touchstart"==k||"touchend"==k,Jb:k,Nb:d,Ob:function(c){c=c||window.event;for(var l={},k=0;k<c.touches.length;++k){var p=c.touches[k];l[p.identifier]=p}for(k=0;k<c.changedTouches.length;++k)p=c.changedTouches[k],l[p.identifier]=p,p.ac=!0;for(k=0;k<c.targetTouches.length;++k)p=c.targetTouches[k],l[p.identifier].fc=!0;var q=p=Na;F[q+4>>2]=c.ctrlKey;F[q+8>>2]=c.shiftKey;F[q+12>>2]=c.altKey;F[q+16>>2]=c.metaKey;q+=20;var Ga=e.canvas?e.canvas.getBoundingClientRect():
void 0,hb=a.getBoundingClientRect?a.getBoundingClientRect():{left:0,top:0},ib=0;for(k in l){var v=l[k];F[q>>2]=v.identifier;F[q+4>>2]=v.screenX;F[q+8>>2]=v.screenY;F[q+12>>2]=v.clientX;F[q+16>>2]=v.clientY;F[q+20>>2]=v.pageX;F[q+24>>2]=v.pageY;F[q+28>>2]=v.ac;F[q+32>>2]=v.fc;Ga?(F[q+44>>2]=v.clientX-Ga.left,F[q+48>>2]=v.clientY-Ga.top):(F[q+44>>2]=0,F[q+48>>2]=0);F[q+36>>2]=v.clientX-hb.left;F[q+40>>2]=v.clientY-hb.top;q+=52;if(32<=++ib)break}F[p>>2]=ib;R(d,f,p,b)&&c.preventDefault()},Mb:c})}
function gb(a,b,c,d,f,k){a||(a=e.canvas);a={target:P(a),Lb:!1,Jb:k,Nb:d,Ob:function(a){a=a||window.event;R(d,f,0,b)&&a.preventDefault()},Mb:c};O(a)}
function jb(a,b,c,d,f){function k(c){c=c||window.event;db(M,c,a);G[M+72>>3]=c.wheelDeltaX||0;G[M+80>>3]=-(c.wheelDeltaY?c.wheelDeltaY:c.wheelDelta);G[M+88>>3]=0;F[M+96>>2]=0;R(d,9,M,b)&&c.preventDefault()}function l(c){c=c||window.event;var f=M;db(f,c,a);G[f+72>>3]=c.deltaX;G[f+80>>3]=c.deltaY;G[f+88>>3]=c.deltaZ;F[f+96>>2]=c.deltaMode;R(d,9,f,b)&&c.preventDefault()}M||(M=Q(104));O({target:a,Lb:!0,Jb:f,Nb:d,Ob:"wheel"==f?l:k,Mb:c})}
var kb=1,lb=0,mb=[],T=[],nb=[],ob=[],pb=[],U=[],V=[],qb=[],rb={},W=null,bb={},X={},sb={};function Y(a){lb||(lb=a)}function tb(a){for(var b=kb++,c=a.length;c<b;c++)a[c]=null;return b}function ub(a,b){function c(){var a=navigator.userAgent.match(/Chrom(e|ium)\/([0-9]+)\./);return a?parseInt(a[2],10):!1}var d=Q(8),f={handle:d,attributes:b,version:b.Zb,Vb:a};f.Pb=2<=f.version&&(!1===c()||58<=c());a.canvas&&(a.canvas.hc=f);rb[d]=f;("undefined"===typeof b.Xb||b.Xb)&&vb(f);return d}
function vb(a){a||(a=W);if(!a.ec){a.ec=!0;var b=a.Vb;if(2>a.version){var c=b.getExtension("ANGLE_instanced_arrays");c&&(b.vertexAttribDivisor=function(a,b){c.vertexAttribDivisorANGLE(a,b)},b.drawArraysInstanced=function(a,b,d,f){c.drawArraysInstancedANGLE(a,b,d,f)},b.drawElementsInstanced=function(a,b,d,f,k){c.drawElementsInstancedANGLE(a,b,d,f,k)});var d=b.getExtension("OES_vertex_array_object");d&&(b.createVertexArray=function(){return d.createVertexArrayOES()},b.deleteVertexArray=function(a){d.deleteVertexArrayOES(a)},
b.bindVertexArray=function(a){d.bindVertexArrayOES(a)},b.isVertexArray=function(a){return d.isVertexArrayOES(a)});var f=b.getExtension("WEBGL_draw_buffers");f&&(b.drawBuffers=function(a,b){f.drawBuffersWEBGL(a,b)})}b.kc=b.getExtension("EXT_disjoint_timer_query");var k="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic EXT_frag_depth WEBGL_draw_buffers ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear EXT_blend_minmax EXT_shader_texture_lod WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_sRGB WEBGL_compressed_texture_etc1 EXT_disjoint_timer_query WEBGL_compressed_texture_etc WEBGL_compressed_texture_astc EXT_color_buffer_float WEBGL_compressed_texture_s3tc_srgb EXT_disjoint_timer_query_webgl2".split(" ");
(a=b.getSupportedExtensions())&&0<a.length&&b.getSupportedExtensions().forEach(function(a){-1!=k.indexOf(a)&&b.getExtension(a)})}}var ab={},wb,xb,yb=["default","low-power","high-performance"],zb=[];function Ab(a,b,c,d){for(var f=0;f<a;f++){var k=Z[c](),l=k&&tb(d);k?(k.name=l,d[l]=k):Y(1282);F[b+4*f>>2]=l}}
function Bb(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=Z.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>W.version){Y(1282);return}d=Z.getSupportedExtensions();c=null===d?0:2*d.length;break;case 33307:case 33308:if(2>W.version){Y(1280);return}c=33307==a?3:0}if(void 0===c)switch(d=Z.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":Y(1280);return;case "object":if(null===
d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 35097:case 36389:case 34068:c=0;break;default:Y(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)F[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(f){Y(1280);y("GL_INVALID_ENUM in glGetIntegerv: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:Y(1280);return}F[b>>2]=c}else Y(1281)}
function Cb(a){var b=la(a)+1,c=Q(b);C(a,B,c,b);return c}var Db={6402:1,6403:1,6406:1,6407:3,6408:4,6409:1,6410:2,33319:2,33320:2,35904:3,35906:4,36244:1,36248:3,36249:4},Eb={5120:1,5121:1,5122:2,5123:2,5124:4,5125:4,5126:4,5131:2,32819:2,32820:2,33635:2,33640:4,34042:4,35899:4,35902:4,36193:2};
function Fb(a,b,c,d,f){if(b=Db[b]*Eb[a])switch(c=f+d*(c*b+4-1&-4),a){case 5120:return D.subarray(f,c);case 5121:return B.subarray(f,c);case 5122:return E.subarray(f>>1,c>>1);case 5124:return F.subarray(f>>2,c>>2);case 5126:return ra.subarray(f>>2,c>>2);case 5125:case 34042:case 35902:case 33640:case 35899:case 34042:return qa.subarray(f>>2,c>>2);case 5123:case 33635:case 32819:case 32820:case 36193:case 5131:return pa.subarray(f>>1,c>>1);default:Y(1280)}else Y(1280)}
function Gb(a){switch(a){case 5120:return D;case 5121:return B;case 5122:return E;case 5123:case 33635:case 32819:case 32820:case 36193:case 5131:return pa;case 5124:return F;case 5125:case 34042:case 35902:case 33640:case 35899:case 34042:return qa;case 5126:return ra}}var Hb={5122:1,5123:1,5124:2,5125:2,5126:2,5131:1,32819:1,32820:1,33635:1,33640:2,34042:2,35899:2,35902:2,36193:1};
function Ib(a){a=oa(a);var b=buffer.byteLength;try{return-1!==z.grow((a-b)/65536)?(buffer=z.buffer,!0):!1}catch(c){return!1}}for(var Z,Jb=0;256>Jb;Jb++);for(var Kb=0;32>Kb;Kb++)zb.push(Array(Kb));
var Rb=e.asm({},{e:w,Z:function(){},S:function(a){e.___errno_location&&(F[e.___errno_location()>>2]=a);return a},Ha:function(a,b){K=b;try{return Ja.dc(),L(),L(),L(),L(),0}catch(c){return w(c),-c.Yb}},O:function(a,b){K=b;try{var c=L(),d=L(),f=L();for(b=a=0;b<f;b++){for(var k=F[d+8*b>>2],l=F[d+(8*b+4)>>2],m=0;m<l;m++){var n=B[k+m],p=Ia[c];0===n||10===n?((1===c?fa:y)(ka(p,0)),p.length=0):p.push(n)}a+=l}return a}catch(q){return w(q),-q.Yb}},ya:function(a,b){K=b;return 0},qa:function(a,b){K=b;try{return Ja.dc(),
0}catch(c){return w(c),-c.Yb}},G:function(){},D:function(){return window.devicePixelRatio||1},z:function(a,b,c){a=a?P(a):e.canvas;if(!a)return-4;a.getBoundingClientRect?(a=a.getBoundingClientRect(),G[b>>3]=a.right-a.left,G[c>>3]=a.bottom-a.top):(G[b>>3]=a.clientWidth,G[c>>3]=a.clientHeight);return 0},jb:Za,db:function(a,b,c){B.set(B.subarray(b,b+c),a)},Ya:function(a,b){function c(d){Lb(a,d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},Xa:function(a){if(2147418112<a)return!1;for(var b=
Math.max(Za(),16777216);b<a;)536870912>=b?b=oa(2*b):b=Math.min(oa((3*b+2147483648)/4),2147418112);if(!Ib(b))return!1;sa();return!0},T:function(a,b,c){a=$a(a);if(!a)return-4;a.width=b;a.height=c;return 0},Wa:function(a,b,c,d){cb(a,b,c,d,2,"keydown");return 0},Va:function(a,b,c,d){cb(a,b,c,d,1,"keypress");return 0},Ua:function(a,b,c,d){cb(a,b,c,d,3,"keyup");return 0},Ta:function(a,b,c,d){S(a,b,c,d,5,"mousedown");return 0},Sa:function(a,b,c,d){S(a,b,c,d,33,"mouseenter");return 0},Ra:function(a,b,c,d){S(a,
b,c,d,34,"mouseleave");return 0},Qa:function(a,b,c,d){S(a,b,c,d,8,"mousemove");return 0},Pa:function(a,b,c,d){S(a,b,c,d,6,"mouseup");return 0},Oa:function(a,b,c,d){eb(a,b,c,d);return 0},Na:function(a,b,c,d){fb(a,b,c,d,25,"touchcancel");return 0},Ma:function(a,b,c,d){fb(a,b,c,d,23,"touchend");return 0},La:function(a,b,c,d){fb(a,b,c,d,24,"touchmove");return 0},Ka:function(a,b,c,d){fb(a,b,c,d,22,"touchstart");return 0},Ja:function(a,b,c,d){gb(a,b,c,d,31,"webglcontextlost");return 0},Ia:function(a,b,
c,d){gb(a,b,c,d,32,"webglcontextrestored");return 0},Ga:function(a,b,c,d){a=P(a);return"undefined"!==typeof a.onwheel?(jb(a,b,c,d,"wheel"),0):"undefined"!==typeof a.onmousewheel?(jb(a,b,c,d,"mousewheel"),0):-1},R:function(a,b){var c={};b>>=2;c.alpha=!!F[b];c.depth=!!F[b+1];c.stencil=!!F[b+2];c.antialias=!!F[b+3];c.premultipliedAlpha=!!F[b+4];c.preserveDrawingBuffer=!!F[b+5];c.powerPreference=yb[F[b+6]];c.failIfMajorPerformanceCaveat=!!F[b+7];c.Zb=F[b+8];c.mc=F[b+9];c.Xb=F[b+10];c.cc=F[b+11];c.nc=
F[b+12];c.oc=F[b+13];a=$a(a);!a||c.cc?c=0:c=(a=1<c.Zb?a.getContext("webgl2",c):a.getContext("webgl",c)||a.getContext("experimental-webgl",c))&&ub(a,c);return c},Fa:function(a){a>>=2;for(var b=0;14>b;++b)F[a+b]=0;F[a]=F[a+1]=F[a+3]=F[a+4]=F[a+8]=F[a+10]=1},Ea:function(a){W=rb[a];e.jc=Z=W&&W.Vb;return!a||Z?0:-5},h:function(a){Z.activeTexture(a)},Q:function(a,b){Z.attachShader(T[a],V[b])},g:function(a,b){35051==a?Z.Wb=b:35052==a&&(Z.Kb=b);Z.bindBuffer(a,mb[b])},j:function(a,b){Z.bindFramebuffer(a,nb[b])},
P:function(a,b){Z.bindRenderbuffer(a,ob[b])},b:function(a,b){Z.bindTexture(a,pb[b])},N:function(a){Z.bindVertexArray(qb[a])},M:function(a,b,c,d){Z.blendColor(a,b,c,d)},L:function(a,b){Z.blendEquationSeparate(a,b)},K:function(a,b,c,d){Z.blendFuncSeparate(a,b,c,d)},p:function(a,b,c,d,f,k,l,m,n,p){Z.blitFramebuffer(a,b,c,d,f,k,l,m,n,p)},Da:function(a,b,c,d){W.Pb?c?Z.bufferData(a,B,d,c,b):Z.bufferData(a,b,d):Z.bufferData(a,c?B.subarray(c,c+b):b,d)},Ca:function(a,b,c,d){W.Pb?Z.bufferSubData(a,b,B,d,c):
Z.bufferSubData(a,b,B.subarray(d,d+c))},Ba:function(a){Z.clear(a)},Aa:function(a,b,c,d){Z.clearColor(a,b,c,d)},za:function(a){Z.clearDepth(a)},xa:function(a){Z.clearStencil(a)},v:function(a,b,c,d){Z.colorMask(!!a,!!b,!!c,!!d)},wa:function(a){Z.compileShader(V[a])},va:function(a,b,c,d,f,k,l,m){W.Pb?Z.Kb?Z.compressedTexImage2D(a,b,c,d,f,k,l,m):Z.compressedTexImage2D(a,b,c,d,f,k,B,m,l):Z.compressedTexImage2D(a,b,c,d,f,k,m?B.subarray(m,m+l):null)},ua:function(a,b,c,d,f,k,l,m,n){W.Pb?Z.Kb?Z.compressedTexImage3D(a,
b,c,d,f,k,l,m,n):Z.compressedTexImage3D(a,b,c,d,f,k,l,B,n,m):Z.compressedTexImage3D(a,b,c,d,f,k,l,n?B.subarray(n,n+m):null)},ta:function(){var a=tb(T),b=Z.createProgram();b.name=a;T[a]=b;return a},sa:function(a){var b=tb(V);V[b]=Z.createShader(a);return b},J:function(a){Z.cullFace(a)},ra:function(a,b){for(var c=0;c<a;c++){var d=F[b+4*c>>2],f=mb[d];f&&(Z.deleteBuffer(f),f.name=0,mb[d]=null,d==wb&&(wb=0),d==xb&&(xb=0),d==Z.Wb&&(Z.Wb=0),d==Z.Kb&&(Z.Kb=0))}},l:function(a,b){for(var c=0;c<a;++c){var d=
F[b+4*c>>2],f=nb[d];f&&(Z.deleteFramebuffer(f),f.name=0,nb[d]=null)}},I:function(a){if(a){var b=T[a];b?(Z.deleteProgram(b),b.name=0,T[a]=null,X[a]=null):Y(1281)}},o:function(a,b){for(var c=0;c<a;c++){var d=F[b+4*c>>2],f=ob[d];f&&(Z.deleteRenderbuffer(f),f.name=0,ob[d]=null)}},u:function(a){if(a){var b=V[a];b?(Z.deleteShader(b),V[a]=null):Y(1281)}},H:function(a,b){for(var c=0;c<a;c++){var d=F[b+4*c>>2],f=pb[d];f&&(Z.deleteTexture(f),f.name=0,pb[d]=null)}},pa:function(a,b){for(var c=0;c<a;c++){var d=
F[b+4*c>>2];Z.deleteVertexArray(qb[d]);qb[d]=null}},t:function(a){Z.depthFunc(a)},s:function(a){Z.depthMask(!!a)},d:function(a){Z.disable(a)},c:function(a){Z.disableVertexAttribArray(a)},oa:function(a,b,c){Z.drawArrays(a,b,c)},n:function(a,b){for(var c=zb[a],d=0;d<a;d++)c[d]=F[b+4*d>>2];Z.drawBuffers(c)},na:function(a,b,c,d){Z.drawElements(a,b,c,d)},f:function(a){Z.enable(a)},ma:function(a){Z.enableVertexAttribArray(a)},F:function(a){Z.frontFace(a)},la:function(a,b){Ab(a,b,"createBuffer",mb)},E:function(a,
b){Ab(a,b,"createRenderbuffer",ob)},ka:function(a,b){Ab(a,b,"createTexture",pb)},ja:function(a,b){Ab(a,b,"createVertexArray",qb)},ia:function(a,b){return Z.getAttribLocation(T[a],A(b))},r:function(a,b){Bb(a,b)},ha:function(a,b,c,d){a=Z.getProgramInfoLog(T[a]);null===a&&(a="(unknown error)");0<b&&d?(b=C(a,B,d,b),c&&(F[c>>2]=b)):c&&(F[c>>2]=0)},C:function(a,b,c){if(c)if(a>=kb)Y(1281);else{var d=X[a];if(d)if(35716==b)a=Z.getProgramInfoLog(T[a]),null===a&&(a="(unknown error)"),F[c>>2]=a.length+1;else if(35719==
b)F[c>>2]=d.Ub;else if(35722==b){if(-1==d.Rb){a=T[a];var f=Z.getProgramParameter(a,35721);for(b=d.Rb=0;b<f;++b)d.Rb=Math.max(d.Rb,Z.getActiveAttrib(a,b).name.length+1)}F[c>>2]=d.Rb}else if(35381==b){if(-1==d.Sb)for(a=T[a],f=Z.getProgramParameter(a,35382),b=d.Sb=0;b<f;++b)d.Sb=Math.max(d.Sb,Z.getActiveUniformBlockName(a,b).length+1);F[c>>2]=d.Sb}else F[c>>2]=Z.getProgramParameter(T[a],b);else Y(1282)}else Y(1281)},ga:function(a,b,c,d){a=Z.getShaderInfoLog(V[a]);null===a&&(a="(unknown error)");0<b&&
d?(b=C(a,B,d,b),c&&(F[c>>2]=b)):c&&(F[c>>2]=0)},B:function(a,b,c){c?35716==b?(a=Z.getShaderInfoLog(V[a]),null===a&&(a="(unknown error)"),F[c>>2]=a.length+1):35720==b?(a=Z.getShaderSource(V[a]),F[c>>2]=null===a||0==a.length?0:a.length+1):F[c>>2]=Z.getShaderParameter(V[a],b):Y(1281)},fa:function(a){if(sb[a])return sb[a];switch(a){case 7939:var b=Z.getSupportedExtensions();for(var c=[],d=0;d<b.length;++d)c.push(b[d]),c.push("GL_"+b[d]);b=Cb(c.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=
Z.getParameter(a))||Y(1280);b=Cb(b);break;case 7938:b=Z.getParameter(Z.VERSION);b=2<=W.version?"OpenGL ES 3.0 ("+b+")":"OpenGL ES 2.0 ("+b+")";b=Cb(b);break;case 35724:b=Z.getParameter(Z.SHADING_LANGUAGE_VERSION);c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=Cb(b);break;default:return Y(1280),0}return sb[a]=b},k:function(a,b){b=A(b);var c=0;if("]"==b[b.length-1]){var d=b.lastIndexOf("[");c="]"!=b[d+1]?parseInt(b.slice(d+
1)):0;b=b.slice(0,d)}return(a=X[a]&&X[a].$b[b])&&0<=c&&c<a[0]?a[1]+c:-1},ea:function(a){Z.linkProgram(T[a]);var b=T[a];a=X[a]={$b:{},Ub:0,Rb:-1,Sb:-1};for(var c=a.$b,d=Z.getProgramParameter(b,35718),f=0;f<d;++f){var k=Z.getActiveUniform(b,f),l=k.name;a.Ub=Math.max(a.Ub,l.length+1);"]"==l.slice(-1)&&(l=l.slice(0,l.lastIndexOf("[")));var m=Z.getUniformLocation(b,l);if(m){var n=tb(U);c[l]=[k.size,n];U[n]=m;for(var p=1;p<k.size;++p)m=Z.getUniformLocation(b,l+"["+p+"]"),n=tb(U),U[n]=m}}},A:function(a,
b){Z.polygonOffset(a,b)},m:function(a){Z.readBuffer(a)},da:function(a,b,c,d){Z.renderbufferStorage(a,b,c,d)},y:function(a,b,c,d,f){Z.renderbufferStorageMultisample(a,b,c,d,f)},ca:function(a,b,c,d){Z.scissor(a,b,c,d)},ba:function(a,b,c,d){for(var f="",k=0;k<b;++k){var l=d?F[d+4*k>>2]:-1;f+=A(F[c+4*k>>2],0>l?void 0:l)}Z.shaderSource(V[a],f)},aa:function(a,b,c){Z.stencilFunc(a,b,c)},x:function(a,b,c,d){Z.stencilFuncSeparate(a,b,c,d)},q:function(a){Z.stencilMask(a)},$:function(a,b,c){Z.stencilOp(a,b,
c)},w:function(a,b,c,d){Z.stencilOpSeparate(a,b,c,d)},_:function(a,b,c,d,f,k,l,m,n){W.Pb?Z.Kb?Z.texImage2D(a,b,c,d,f,k,l,m,n):0!=n?Z.texImage2D(a,b,c,d,f,k,l,m,Gb(m),n>>(Hb[m]|0)):Z.texImage2D(a,b,c,d,f,k,l,m,null):Z.texImage2D(a,b,c,d,f,k,l,m,n?Fb(m,l,d,f,n):null)},ib:function(a,b,c,d,f,k,l,m,n,p){Z.Kb?Z.texImage3D(a,b,c,d,f,k,l,m,n,p):0!=p?Z.texImage3D(a,b,c,d,f,k,l,m,n,Gb(n),p>>(Hb[n]|0)):Z.texImage3D(a,b,c,d,f,k,l,m,n,null)},Y:function(a,b,c){Z.texParameterf(a,b,c)},i:function(a,b,c){Z.texParameteri(a,
b,c)},X:function(a,b,c,d,f,k,l,m,n){if(W.Pb)Z.Kb?Z.texSubImage2D(a,b,c,d,f,k,l,m,n):0!=n?Z.texSubImage2D(a,b,c,d,f,k,l,m,Gb(m),n>>(Hb[m]|0)):Z.texSubImage2D(a,b,c,d,f,k,l,m,null);else{var p=null;n&&(p=Fb(m,l,f,k,n));Z.texSubImage2D(a,b,c,d,f,k,l,m,p)}},W:function(a,b,c,d,f,k,l,m,n,p,q){Z.Kb?Z.texSubImage3D(a,b,c,d,f,k,l,m,n,p,q):0!=q?Z.texSubImage3D(a,b,c,d,f,k,l,m,n,p,Gb(p),q>>(Hb[p]|0)):Z.texSubImage3D(a,b,c,d,f,k,l,m,n,p,null)},V:function(a,b){Z.uniform1i(U[a],b)},hb:function(a){Z.useProgram(T[a])},
gb:function(a,b){Z.vertexAttribDivisor(a,b)},fb:function(a,b,c,d,f,k){Z.vertexAttribPointer(a,b,c,!!d,f,k)},eb:function(a,b,c,d){Z.viewport(a,b,c,d)},cb:function(){window.addEventListener("beforeunload",function(a){0!=Mb()&&(a.preventDefault(),a.returnValue=" ")})},bb:function(){return e.Qb?e.Qb.bufferSize:0},ab:function(a,b,c){e.Ib=null;e.Qb=null;"undefined"!==typeof AudioContext?(e.Ib=new AudioContext({sampleRate:a,latencyHint:"interactive"}),console.log("sokol_audio.h: created AudioContext")):
"undefined"!==typeof webkitAudioContext?(e.Ib=new webkitAudioContext({sampleRate:a,latencyHint:"interactive"}),console.log("sokol_audio.h: created webkitAudioContext")):(e.Ib=null,console.log("sokol_audio.h: no WebAudio support"));return e.Ib?(console.log("sokol_audio.h: sample rate ",e.Ib.sampleRate),e.Qb=e.Ib.createScriptProcessor(c,0,b),e.Qb.onaudioprocess=function(a){var b=a.outputBuffer.length,c=Nb(b);if(c)for(var d=a.outputBuffer.numberOfChannels,m=0;m<d;m++)for(var n=a.outputBuffer.getChannelData(m),
p=0;p<b;p++)n[p]=ra[(c>>2)+(d*p+m)]},e.Qb.connect(e.Ib.destination),a=function(){e.Ib&&"suspended"===e.Ib.state&&e.Ib.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchstart",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),1):0},$a:function(){return e.Ib?e.Ib.sampleRate:0},_a:function(a,b){b=A(b);var c=new XMLHttpRequest;c.open("HEAD",b);c.onreadystatechange=function(){if(this.readyState==this.DONE)if(200==this.status){var b=this.getResponseHeader("Content-Length");
Ob(a,b)}else Pb(a)};c.send()},U:function(a,b,c,d,f,k){b=A(b);var l=new XMLHttpRequest;l.open("GET",b);l.responseType="arraybuffer";var m=!(0==c&&d==f);m&&l.setRequestHeader("Range","bytes="+c+"-"+(c+d));l.onreadystatechange=function(){if(this.readyState==this.DONE)if(206==this.status||200==this.status&&!m){var b=new Uint8Array(l.response);B.set(b,k);Qb(a,d)}else Pb(a)};l.send()},Za:function(){w("OOM")},a:548832},buffer);e.asm=Rb;
e.___em_js__sapp_js_create_textfield=function(){return e.asm.kb.apply(null,arguments)};e.___em_js__sapp_js_focus_textfield=function(){return e.asm.lb.apply(null,arguments)};e.___em_js__sapp_js_hook_beforeunload=function(){return e.asm.mb.apply(null,arguments)};e.___em_js__sapp_js_unfocus_textfield=function(){return e.asm.nb.apply(null,arguments)};e.___em_js__saudio_js_buffer_frames=function(){return e.asm.ob.apply(null,arguments)};e.___em_js__saudio_js_init=function(){return e.asm.pb.apply(null,arguments)};
e.___em_js__saudio_js_sample_rate=function(){return e.asm.qb.apply(null,arguments)};e.___em_js__sfetch_js_send_head_request=function(){return e.asm.rb.apply(null,arguments)};e.___em_js__sfetch_js_send_range_request=function(){return e.asm.sb.apply(null,arguments)};e.___em_js__stm_js_perfnow=function(){return e.asm.tb.apply(null,arguments)};e.__sapp_emsc_notify_keyboard_hidden=function(){return e.asm.ub.apply(null,arguments)};
var Mb=e.__sapp_html5_get_ask_leave_site=function(){return e.asm.vb.apply(null,arguments)},Nb=e.__saudio_emsc_pull=function(){return e.asm.wb.apply(null,arguments)},Pb=e.__sfetch_emsc_failed=function(){return e.asm.xb.apply(null,arguments)},Ob=e.__sfetch_emsc_head_response=function(){return e.asm.yb.apply(null,arguments)},Qb=e.__sfetch_emsc_range_response=function(){return e.asm.zb.apply(null,arguments)};e._free=function(){return e.asm.Ab.apply(null,arguments)};
e._main=function(){return e.asm.Bb.apply(null,arguments)};var Q=e._malloc=function(){return e.asm.Cb.apply(null,arguments)},na=e.stackAlloc=function(){return e.asm.Hb.apply(null,arguments)},Lb=e.dynCall_idi=function(){return e.asm.Db.apply(null,arguments)},R=e.dynCall_iiii=function(){return e.asm.Eb.apply(null,arguments)};e.dynCall_v=function(){return e.asm.Fb.apply(null,arguments)};e.dynCall_vi=function(){return e.asm.Gb.apply(null,arguments)};e.asm=Rb;
function x(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}x.prototype=Error();x.prototype.constructor=x;I=function Sb(){e.calledRun||Tb();e.calledRun||(I=Sb)};
e.callMain=function(a){a=a||[];var b=a.length+1,c=na(4*(b+1));F[c>>2]=ma(e.thisProgram);for(var d=1;d<b;d++)F[(c>>2)+d]=ma(a[d-1]);F[(c>>2)+b]=0;try{var f=e._main(b,c,0);if(!e.noExitRuntime||0!==f){if(!e.noExitRuntime&&(ia=!0,e.onExit))e.onExit(f);e.quit(f,new x(f))}}catch(k){k instanceof x||("SimulateInfiniteLoop"==k?e.noExitRuntime=!0:((a=k)&&"object"===typeof k&&k.stack&&(a=[k,k.stack]),y("exception thrown: "+a),e.quit(1,k)))}finally{}};
function Tb(a){function b(){if(!e.calledRun&&(e.calledRun=!0,!ia)){ua(wa);ua(xa);if(e.onRuntimeInitialized)e.onRuntimeInitialized();e._main&&Ub&&e.callMain(a);if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var b=e.postRun.shift();za.unshift(b)}ua(za)}}a=a||e.arguments;if(!(0<H)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Aa();ua(va);0<H||e.calledRun||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},
1);b()},1)):b())}}e.run=Tb;function w(a){if(e.onAbort)e.onAbort(a);void 0!==a?(fa(a),y(a),a='"'+a+'"'):a="";ia=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}e.abort=w;if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();var Ub=!0;e.noInitialRun&&(Ub=!1);e.noExitRuntime=!0;Tb();
