var d;d||(d=typeof Module !== 'undefined' ? Module : {});var g={},h;for(h in d)d.hasOwnProperty(h)&&(g[h]=d[h]);d.arguments=[];d.thisProgram="./this.program";d.quit=function(a,b){throw b;};d.preRun=[];d.postRun=[];var m=!1,n=!1,p=!1,q=!1;m="object"===typeof window;n="function"===typeof importScripts;p="object"===typeof process&&"function"===typeof require&&!m&&!n;q=!m&&!p&&!n;var r="";
if(p){r=__dirname+"/";var t,u;d.read=function(a,b){t||(t=require("fs"));u||(u=require("path"));a=u.normalize(a);a=t.readFileSync(a);return b?a:a.toString()};d.readBinary=function(a){a=d.read(a,!0);a.buffer||(a=new Uint8Array(a));a.buffer||v("Assertion failed: undefined");return a};1<process.argv.length&&(d.thisProgram=process.argv[1].replace(/\\/g,"/"));d.arguments=process.argv.slice(2);"undefined"!==typeof module&&(module.exports=d);process.on("uncaughtException",function(a){if(!(a instanceof w))throw a;
});process.on("unhandledRejection",v);d.quit=function(a){process.exit(a)};d.inspect=function(){return"[Emscripten Module object]"}}else if(q)"undefined"!=typeof read&&(d.read=function(a){return read(a)}),d.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");"object"===typeof a||v("Assertion failed: undefined");return a},"undefined"!=typeof scriptArgs?d.arguments=scriptArgs:"undefined"!=typeof arguments&&(d.arguments=arguments),"function"===
typeof quit&&(d.quit=function(a){quit(a)});else if(m||n)n?r=self.location.href:document.currentScript&&(r=document.currentScript.src),r=0!==r.indexOf("blob:")?r.substr(0,r.lastIndexOf("/")+1):"",d.read=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},n&&(d.readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),d.readAsync=function(a,b,c){var e=new XMLHttpRequest;e.open("GET",
a,!0);e.responseType="arraybuffer";e.onload=function(){200==e.status||0==e.status&&e.response?b(e.response):c()};e.onerror=c;e.send(null)},d.setWindowTitle=function(a){document.title=a};var x=d.print||("undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null),y=d.printErr||("undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||x);for(h in g)g.hasOwnProperty(h)&&(d[h]=g[h]);g=void 0;
var aa={"f64-rem":function(a,b){return a%b},"debugger":function(){debugger}};"object"!==typeof WebAssembly&&y("no native wasm support detected");var z,A=!1,B="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function C(a){if(a){for(var b=D,c=a+void 0,e=a;b[e]&&!(e>=c);)++e;if(16<e-a&&b.subarray&&B)a=B.decode(b.subarray(a,e));else{for(c="";a<e;){var f=b[a++];if(f&128){var k=b[a++]&63;if(192==(f&224))c+=String.fromCharCode((f&31)<<6|k);else{var l=b[a++]&63;f=224==(f&240)?(f&15)<<12|k<<6|l:(f&7)<<18|k<<12|l<<6|b[a++]&63;65536>f?c+=String.fromCharCode(f):(f-=65536,c+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else c+=String.fromCharCode(f)}a=c}}else a="";return a}
function ba(a,b,c,e){if(0<e){e=c+e-1;for(var f=0;f<a.length;++f){var k=a.charCodeAt(f);if(55296<=k&&57343>=k){var l=a.charCodeAt(++f);k=65536+((k&1023)<<10)|l&1023}if(127>=k){if(c>=e)break;b[c++]=k}else{if(2047>=k){if(c+1>=e)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=e)break;b[c++]=224|k>>12}else{if(c+3>=e)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0}}
function ca(a){for(var b=0,c=0;c<a.length;++c){var e=a.charCodeAt(c);55296<=e&&57343>=e&&(e=65536+((e&1023)<<10)|a.charCodeAt(++c)&1023);127>=e?++b:b=2047>=e?b+2:65535>=e?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function da(a){var b=ca(a)+1,c=ea(b);ba(a,fa,c,b);return c}var buffer,fa,D,E,F,G=d.TOTAL_MEMORY||134217728;5242880>G&&y("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+G+"! (TOTAL_STACK=5242880)");
d.buffer?buffer=d.buffer:("object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(z=new WebAssembly.Memory({initial:G/65536,maximum:G/65536}),buffer=z.buffer):buffer=new ArrayBuffer(G),d.buffer=buffer);d.HEAP8=fa=new Int8Array(buffer);d.HEAP16=new Int16Array(buffer);d.HEAP32=E=new Int32Array(buffer);d.HEAPU8=D=new Uint8Array(buffer);d.HEAPU16=new Uint16Array(buffer);d.HEAPU32=new Uint32Array(buffer);d.HEAPF32=new Float32Array(buffer);d.HEAPF64=F=new Float64Array(buffer);E[812]=5246384;
function H(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.la;"number"===typeof c?void 0===b.T?d.dynCall_v(c):d.dynCall_vi(c,b.T):c(void 0===b.T?null:b.T)}}}var ha=[],ia=[],ja=[],ka=[],la=[],I=!1;function ma(){var a=d.preRun.shift();ha.unshift(a)}var J=0,K=null,L=null;d.preloadedImages={};d.preloadedAudios={};
function na(){var a=M;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var M="clear-emsc.wasm";if(!na()){var oa=M;M=d.locateFile?d.locateFile(oa,r):r+oa}function pa(){try{if(d.wasmBinary)return new Uint8Array(d.wasmBinary);if(d.readBinary)return d.readBinary(M);throw"both async and sync fetching of the wasm failed";}catch(a){v(a)}}
function qa(){return d.wasmBinary||!m&&!n||"function"!==typeof fetch?new Promise(function(a){a(pa())}):fetch(M,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+M+"'";return a.arrayBuffer()}).catch(function(){return pa()})}
function ra(a){function b(a){d.asm=a.exports;J--;d.monitorRunDependencies&&d.monitorRunDependencies(J);0==J&&(null!==K&&(clearInterval(K),K=null),L&&(a=L,L=null,a()))}function c(a){b(a.instance)}function e(a){qa().then(function(a){return WebAssembly.instantiate(a,f)}).then(a,function(a){y("failed to asynchronously prepare wasm: "+a);v(a)})}var f={env:a,global:{NaN:NaN,Infinity:Infinity},"global.Math":Math,asm2wasm:aa};J++;d.monitorRunDependencies&&d.monitorRunDependencies(J);if(d.instantiateWasm)try{return d.instantiateWasm(f,
b)}catch(k){return y("Module.instantiateWasm callback failed with error: "+k),!1}d.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||na()||"function"!==typeof fetch?e(c):WebAssembly.instantiateStreaming(fetch(M,{credentials:"same-origin"}),f).then(c,function(a){y("wasm streaming compile failed: "+a);y("falling back to ArrayBuffer instantiation");e(c)});return{}}
d.asm=function(a,b){b.memory=z;b.table=new WebAssembly.Table({initial:4,maximum:4,element:"anyfunc"});b.__memory_base=1024;b.__table_base=0;return ra(b)};var N=0,sa=!1;function ta(){for(var a=O.length-1;0<=a;--a)ua(a);O=[];P=[]}function Q(a){try{if(!a)return window;"number"===typeof a&&(a=C(a));return"#window"===a?window:"#document"===a?document:"#screen"===a?window.screen:"#canvas"===a?d.canvas:"string"===typeof a?document.getElementById(a):a}catch(b){return null}}var P=[];
function va(){if(R&&wa.Y)for(var a=0;a<P.length;++a){var b=P[a];P.splice(a,1);--a;b.qa.apply(this,b.ga)}}var R=0,wa=null,O=[];function ua(a){var b=O[a];b.target.removeEventListener(b.S,b.$,b.X);O.splice(a,1)}function xa(a){function b(b){++R;wa=a;va();a.ba(b);va();--R}if(a.Z)a.$=b,a.target.addEventListener(a.S,b,a.X),O.push(a),sa||(ka.push(ta),sa=!0);else for(var c=0;c<O.length;++c)O[c].target==a.target&&O[c].S==a.S&&ua(c--)}
function ya(a){v("Cannot enlarge memory arrays to size "+a+" bytes. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value "+G+", (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ")}
function za(a,b,c,e){N||(N=S(36));a=Q(a);xa({target:a,Y:!1,S:"resize",Z:e,ba:function(c){c=c||window.event;if(c.target==a){var f=0<window.pageXOffset||0<window.pageYOffset?[window.pageXOffset,window.pageYOffset]:"undefined"!==typeof document.documentElement.scrollLeft||"undefined"!==typeof document.documentElement.scrollTop?[document.documentElement.scrollLeft,document.documentElement.scrollTop]:[document.body.scrollLeft|0,document.body.scrollTop|0],l=N;E[l>>2]=c.detail;E[l+4>>2]=document.body.clientWidth;
E[l+8>>2]=document.body.clientHeight;E[l+12>>2]=window.innerWidth;E[l+16>>2]=window.innerHeight;E[l+20>>2]=window.outerWidth;E[l+24>>2]=window.outerHeight;E[l+28>>2]=f[0];E[l+32>>2]=f[1];Aa(e,10,l,b)&&c.preventDefault()}},X:c})}var Ba=0,Ca=[],Da=[],Ea={},T=null,U={},V={};function W(a){Ba||(Ba=a)}
function Fa(a,b){function c(){var a=navigator.userAgent.match(/Chrom(e|ium)\/([0-9]+)\./);return a?parseInt(a[2],10):!1}var e=S(8),f={handle:e,attributes:b,version:b.W,U:a};f.pa=2<=f.version&&(!1===c()||58<=c());a.canvas&&(a.canvas.fa=f);Ea[e]=f;("undefined"===typeof b.V||b.V)&&Ga(f);return e}
function Ga(a){a||(a=T);if(!a.da){a.da=!0;var b=a.U;if(2>a.version){var c=b.getExtension("ANGLE_instanced_arrays");c&&(b.vertexAttribDivisor=function(a,b){c.vertexAttribDivisorANGLE(a,b)},b.drawArraysInstanced=function(a,b,e,f){c.drawArraysInstancedANGLE(a,b,e,f)},b.drawElementsInstanced=function(a,b,e,f,k){c.drawElementsInstancedANGLE(a,b,e,f,k)});var e=b.getExtension("OES_vertex_array_object");e&&(b.createVertexArray=function(){return e.createVertexArrayOES()},b.deleteVertexArray=function(a){e.deleteVertexArrayOES(a)},
b.bindVertexArray=function(a){e.bindVertexArrayOES(a)},b.isVertexArray=function(a){return e.isVertexArrayOES(a)});var f=b.getExtension("WEBGL_draw_buffers");f&&(b.drawBuffers=function(a,b){f.drawBuffersWEBGL(a,b)})}b.ka=b.getExtension("EXT_disjoint_timer_query");var k="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic EXT_frag_depth WEBGL_draw_buffers ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear EXT_blend_minmax EXT_shader_texture_lod WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_sRGB WEBGL_compressed_texture_etc1 EXT_disjoint_timer_query WEBGL_compressed_texture_etc WEBGL_compressed_texture_astc EXT_color_buffer_float WEBGL_compressed_texture_s3tc_srgb EXT_disjoint_timer_query_webgl2".split(" ");
(a=b.getSupportedExtensions())&&0<a.length&&b.getSupportedExtensions().forEach(function(a){-1!=k.indexOf(a)&&b.getExtension(a)})}}var Ha={},Ia=["default","low-power","high-performance"];
function Ja(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var e=X.getParameter(34467);c=e?e.length:0;break;case 33309:if(2>T.version){W(1282);return}c=2*X.getSupportedExtensions().length;break;case 33307:case 33308:if(2>T.version){W(1280);return}c=33307==a?3:0}if(void 0===c)switch(e=X.getParameter(a),typeof e){case "number":c=e;break;case "boolean":c=e?1:0;break;case "string":W(1280);return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 35097:case 36389:case 34068:c=
0;break;default:W(1280);return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)E[b+4*a>>2]=e[a];return}try{c=e.name|0}catch(f){W(1280);y("GL_INVALID_ENUM in glGetIntegerv: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:W(1280);return}E[b>>2]=c}else W(1281)}function Y(a){var b=ca(a)+1,c=S(b);ba(a,D,c,b);return c}for(var X,Ka=0;256>Ka;Ka++);
var Ma=d.asm({},{q:v,p:function(a){d.___errno_location&&(E[d.___errno_location()>>2]=a);return a},m:function(a,b,c){a=a?Q(a):d.canvas;if(!a)return-4;a.getBoundingClientRect?(a=a.getBoundingClientRect(),F[b>>3]=a.right-a.left,F[c>>3]=a.bottom-a.top):(F[b>>3]=a.clientWidth,F[c>>3]=a.clientHeight);return 0},A:function(){return G},g:function(a,b){function c(e){La(a,e,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},s:function(a){ya(a)},f:function(a,b,c){"number"===typeof a&&(a=C(a));a=a&&
"#canvas"!==a?"undefined"!==typeof Ha&&U[a]?U[a]:Q(a):"undefined"!==typeof Ha&&U.canvas?U.canvas:d.canvas;if(!a)return-4;a.width=b;a.height=c;return 0},r:function(a,b,c,e){za(a,b,c,e);return 0},e:function(a,b){var c={};b>>=2;c.alpha=!!E[b];c.depth=!!E[b+1];c.stencil=!!E[b+2];c.antialias=!!E[b+3];c.premultipliedAlpha=!!E[b+4];c.preserveDrawingBuffer=!!E[b+5];c.powerPreference=Ia[E[b+6]];c.failIfMajorPerformanceCaveat=!!E[b+7];c.W=E[b+8];c.ma=E[b+9];c.V=E[b+10];c.aa=E[b+11];c.na=E[b+12];c.oa=E[b+13];
a=(a=C(a))&&"#canvas"!==a||!d.canvas?U[a]?U[a].ea:Q(a):d.canvas.id&&U[d.canvas.id]?U[d.canvas.id].ea||Q(d.canvas.id):d.canvas;!a||c.aa?c=0:c=(a=1<c.W?a.getContext("webgl2",c):a.getContext("webgl",c)||a.getContext("experimental-webgl",c))&&Fa(a,c);return c},L:function(a){a>>=2;for(var b=0;14>b;++b)E[a+b]=0;E[a]=E[a+1]=E[a+3]=E[a+4]=E[a+8]=E[a+10]=1},K:function(a){T=Ea[a];d.ha=X=T&&T.U;return!a||X?0:-5},o:function(a,b){35051==a?X.ia=b:35052==a&&(X.ja=b);X.bindBuffer(a,Ca[b])},n:function(a,b){X.bindFramebuffer(a,
Da[b])},J:function(a,b,c,e){X.blendColor(a,b,c,e)},I:function(a,b){X.blendEquationSeparate(a,b)},H:function(a,b,c,e){X.blendFuncSeparate(a,b,c,e)},G:function(a){X.clear(a)},F:function(a,b,c,e){X.clearColor(a,b,c,e)},E:function(a){X.clearDepth(a)},D:function(a){X.clearStencil(a)},l:function(a,b,c,e){X.colorMask(!!a,!!b,!!c,!!e)},C:function(a){X.cullFace(a)},k:function(a){X.depthFunc(a)},j:function(a){X.depthMask(!!a)},c:function(a){X.disable(a)},b:function(a){X.disableVertexAttribArray(a)},d:function(a){X.enable(a)},
B:function(a){X.frontFace(a)},i:function(a,b){Ja(a,b)},z:function(a){if(V[a])return V[a];switch(a){case 7939:var b=X.getSupportedExtensions();for(var c=[],e=0;e<b.length;++e)c.push(b[e]),c.push("GL_"+b[e]);b=Y(c.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=X.getParameter(a))||W(1280);b=Y(b);break;case 7938:b=X.getParameter(X.VERSION);b=2<=T.version?"OpenGL ES 3.0 ("+b+")":"OpenGL ES 2.0 ("+b+")";b=Y(b);break;case 35724:b=X.getParameter(X.SHADING_LANGUAGE_VERSION);c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);
null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=Y(b);break;default:return W(1280),0}return V[a]=b},y:function(a,b){X.polygonOffset(a,b)},x:function(a,b,c,e){X.scissor(a,b,c,e)},w:function(a,b,c){X.stencilFunc(a,b,c)},h:function(a){X.stencilMask(a)},v:function(a,b,c){X.stencilOp(a,b,c)},u:function(a,b,c,e){X.viewport(a,b,c,e)},t:ya,a:3248},buffer);d.asm=Ma;d._free=function(){return d.asm.M.apply(null,arguments)};d._main=function(){return d.asm.N.apply(null,arguments)};
var S=d._malloc=function(){return d.asm.O.apply(null,arguments)},ea=d.stackAlloc=function(){return d.asm.R.apply(null,arguments)},La=d.dynCall_idi=function(){return d.asm.P.apply(null,arguments)},Aa=d.dynCall_iiii=function(){return d.asm.Q.apply(null,arguments)};d.asm=Ma;function w(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}w.prototype=Error();w.prototype.constructor=w;L=function Na(){d.calledRun||Z();d.calledRun||(L=Na)};
d.callMain=function(a){a=a||[];I||(I=!0,H(ia));var b=a.length+1,c=ea(4*(b+1));E[c>>2]=da(d.thisProgram);for(var e=1;e<b;e++)E[(c>>2)+e]=da(a[e-1]);E[(c>>2)+b]=0;try{var f=d._main(b,c,0);if(!d.noExitRuntime||0!==f){if(!d.noExitRuntime&&(A=!0,H(ka),d.onExit))d.onExit(f);d.quit(f,new w(f))}}catch(k){k instanceof w||("SimulateInfiniteLoop"==k?d.noExitRuntime=!0:((a=k)&&"object"===typeof k&&k.stack&&(a=[k,k.stack]),y("exception thrown: "+a),d.quit(1,k)))}finally{}};
function Z(a){function b(){if(!d.calledRun&&(d.calledRun=!0,!A)){I||(I=!0,H(ia));H(ja);if(d.onRuntimeInitialized)d.onRuntimeInitialized();d._main&&Oa&&d.callMain(a);if(d.postRun)for("function"==typeof d.postRun&&(d.postRun=[d.postRun]);d.postRun.length;){var b=d.postRun.shift();la.unshift(b)}H(la)}}a=a||d.arguments;if(!(0<J)){if(d.preRun)for("function"==typeof d.preRun&&(d.preRun=[d.preRun]);d.preRun.length;)ma();H(ha);0<J||d.calledRun||(d.setStatus?(d.setStatus("Running..."),setTimeout(function(){setTimeout(function(){d.setStatus("")},
1);b()},1)):b())}}d.run=Z;function v(a){if(d.onAbort)d.onAbort(a);void 0!==a?(x(a),y(a),a=JSON.stringify(a)):a="";A=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}d.abort=v;if(d.preInit)for("function"==typeof d.preInit&&(d.preInit=[d.preInit]);0<d.preInit.length;)d.preInit.pop()();var Oa=!0;d.noInitialRun&&(Oa=!1);d.noExitRuntime=!0;Z();
