var e;e||(e=typeof Module !== 'undefined' ? Module : {});var f={},h;for(h in e)e.hasOwnProperty(h)&&(f[h]=e[h]);e.arguments=[];e.thisProgram="./this.program";e.quit=function(a,b){throw b;};e.preRun=[];e.postRun=[];var m=!1,n=!1,p=!1,aa=!1;m="object"===typeof window;n="function"===typeof importScripts;p="object"===typeof process&&"function"===typeof require&&!m&&!n;aa=!m&&!p&&!n;var q="";
if(p){q=__dirname+"/";var r,t;e.read=function(a,b){r||(r=require("fs"));t||(t=require("path"));a=t.normalize(a);a=r.readFileSync(a);return b?a:a.toString()};e.readBinary=function(a){a=e.read(a,!0);a.buffer||(a=new Uint8Array(a));a.buffer||u("Assertion failed: undefined");return a};1<process.argv.length&&(e.thisProgram=process.argv[1].replace(/\\/g,"/"));e.arguments=process.argv.slice(2);"undefined"!==typeof module&&(module.exports=e);process.on("uncaughtException",function(a){if(!(a instanceof v))throw a;
});process.on("unhandledRejection",u);e.quit=function(a){process.exit(a)};e.inspect=function(){return"[Emscripten Module object]"}}else if(aa)"undefined"!=typeof read&&(e.read=function(a){return read(a)}),e.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");"object"===typeof a||u("Assertion failed: undefined");return a},"undefined"!=typeof scriptArgs?e.arguments=scriptArgs:"undefined"!=typeof arguments&&(e.arguments=arguments),"function"===
typeof quit&&(e.quit=function(a){quit(a)});else if(m||n)n?q=self.location.href:document.currentScript&&(q=document.currentScript.src),q=0!==q.indexOf("blob:")?q.substr(0,q.lastIndexOf("/")+1):"",e.read=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},n&&(e.readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),e.readAsync=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",
a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)},e.setWindowTitle=function(a){document.title=a};var ba=e.print||("undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null),w=e.printErr||("undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||ba);for(h in f)f.hasOwnProperty(h)&&(e[h]=f[h]);f=void 0;
var ca={"f64-rem":function(a,b){return a%b},"debugger":function(){debugger}};"object"!==typeof WebAssembly&&w("no native wasm support detected");var y,z=!1,da="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function A(a,b){if(a){var c=B,d=a+b;for(b=a;c[b]&&!(b>=d);)++b;if(16<b-a&&c.subarray&&da)a=da.decode(c.subarray(a,b));else{for(d="";a<b;){var g=c[a++];if(g&128){var l=c[a++]&63;if(192==(g&224))d+=String.fromCharCode((g&31)<<6|l);else{var k=c[a++]&63;g=224==(g&240)?(g&15)<<12|l<<6|k:(g&7)<<18|l<<12|k<<6|c[a++]&63;65536>g?d+=String.fromCharCode(g):(g-=65536,d+=String.fromCharCode(55296|g>>10,56320|g&1023))}}else d+=String.fromCharCode(g)}a=d}}else a="";return a}
function C(a,b,c,d){if(!(0<d))return 0;var g=c;d=c+d-1;for(var l=0;l<a.length;++l){var k=a.charCodeAt(l);if(55296<=k&&57343>=k){var x=a.charCodeAt(++l);k=65536+((k&1023)<<10)|x&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-g}
function ea(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function ha(a){var b=ea(a)+1,c=ia(b);C(a,ja,c,b);return c}var buffer,ja,B,D,E,F=e.TOTAL_MEMORY||134217728;5242880>F&&w("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+F+"! (TOTAL_STACK=5242880)");
e.buffer?buffer=e.buffer:("object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(y=new WebAssembly.Memory({initial:F/65536,maximum:F/65536}),buffer=y.buffer):buffer=new ArrayBuffer(F),e.buffer=buffer);e.HEAP8=ja=new Int8Array(buffer);e.HEAP16=new Int16Array(buffer);e.HEAP32=D=new Int32Array(buffer);e.HEAPU8=B=new Uint8Array(buffer);e.HEAPU16=new Uint16Array(buffer);e.HEAPU32=new Uint32Array(buffer);e.HEAPF32=new Float32Array(buffer);e.HEAPF64=E=new Float64Array(buffer);D[872]=5246624;
function G(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.Qa;"number"===typeof c?void 0===b.va?e.dynCall_v(c):e.dynCall_vi(c,b.va):c(void 0===b.va?null:b.va)}}}var ka=[],la=[],ma=[],na=[],oa=[],H=!1;function pa(){var a=e.preRun.shift();ka.unshift(a)}var I=0,J=null,K=null;e.preloadedImages={};e.preloadedAudios={};
function qa(){var a=L;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var L="triangle-emsc.wasm";if(!qa()){var ra=L;L=e.locateFile?e.locateFile(ra,q):q+ra}function sa(){try{if(e.wasmBinary)return new Uint8Array(e.wasmBinary);if(e.readBinary)return e.readBinary(L);throw"both async and sync fetching of the wasm failed";}catch(a){u(a)}}
function ta(){return e.wasmBinary||!m&&!n||"function"!==typeof fetch?new Promise(function(a){a(sa())}):fetch(L,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+L+"'";return a.arrayBuffer()}).catch(function(){return sa()})}
function ua(a){function b(a){e.asm=a.exports;I--;e.monitorRunDependencies&&e.monitorRunDependencies(I);0==I&&(null!==J&&(clearInterval(J),J=null),K&&(a=K,K=null,a()))}function c(a){b(a.instance)}function d(a){ta().then(function(a){return WebAssembly.instantiate(a,g)}).then(a,function(a){w("failed to asynchronously prepare wasm: "+a);u(a)})}var g={env:a,global:{NaN:NaN,Infinity:Infinity},"global.Math":Math,asm2wasm:ca};I++;e.monitorRunDependencies&&e.monitorRunDependencies(I);if(e.instantiateWasm)try{return e.instantiateWasm(g,
b)}catch(l){return w("Module.instantiateWasm callback failed with error: "+l),!1}e.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||qa()||"function"!==typeof fetch?d(c):WebAssembly.instantiateStreaming(fetch(L,{credentials:"same-origin"}),g).then(c,function(a){w("wasm streaming compile failed: "+a);w("falling back to ArrayBuffer instantiation");d(c)});return{}}
e.asm=function(a,b){b.memory=y;b.table=new WebAssembly.Table({initial:4,maximum:4,element:"anyfunc"});b.__memory_base=1024;b.__table_base=0;return ua(b)};var va=0,wa=!1;function xa(){for(var a=M.length-1;0<=a;--a)ya(a);M=[];N=[]}function O(a){try{if(!a)return window;"number"===typeof a&&(a=A(a));return"#window"===a?window:"#document"===a?document:"#screen"===a?window.screen:"#canvas"===a?e.canvas:"string"===typeof a?document.getElementById(a):a}catch(b){return null}}var N=[];
function za(){if(Aa&&Ba.Da)for(var a=0;a<N.length;++a){var b=N[a];N.splice(a,1);--a;b.Ua.apply(this,b.La)}}var Aa=0,Ba=null,M=[];function ya(a){var b=M[a];b.target.removeEventListener(b.ua,b.Fa,b.Ca);M.splice(a,1)}function Ca(a){function b(b){++Aa;Ba=a;za();a.Ha(b);za();--Aa}if(a.Ea)a.Fa=b,a.target.addEventListener(a.ua,b,a.Ca),M.push(a),wa||(na.push(xa),wa=!0);else for(var c=0;c<M.length;++c)M[c].target==a.target&&M[c].ua==a.ua&&ya(c--)}
function Da(a){u("Cannot enlarge memory arrays to size "+a+" bytes. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value "+F+", (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ")}
function Ea(a,b,c,d){va||(va=Fa(36));a=O(a);Ca({target:a,Da:!1,ua:"resize",Ea:d,Ha:function(c){c=c||window.event;if(c.target==a){var g=0<window.pageXOffset||0<window.pageYOffset?[window.pageXOffset,window.pageYOffset]:"undefined"!==typeof document.documentElement.scrollLeft||"undefined"!==typeof document.documentElement.scrollTop?[document.documentElement.scrollLeft,document.documentElement.scrollTop]:[document.body.scrollLeft|0,document.body.scrollTop|0],k=va;D[k>>2]=c.detail;D[k+4>>2]=document.body.clientWidth;
D[k+8>>2]=document.body.clientHeight;D[k+12>>2]=window.innerWidth;D[k+16>>2]=window.innerHeight;D[k+20>>2]=window.outerWidth;D[k+24>>2]=window.outerHeight;D[k+28>>2]=g[0];D[k+32>>2]=g[1];Ga(d,10,k,b)&&c.preventDefault()}},Ca:c})}var Ha=1,Ia=0,Ja=[],P=[],Ka=[],La=[],Q=[],R=[],Ma={},T=null,U={},V={},Na={};function W(a){Ia||(Ia=a)}function X(a){for(var b=Ha++,c=a.length;c<b;c++)a[c]=null;return b}
function Oa(a,b){function c(){var a=navigator.userAgent.match(/Chrom(e|ium)\/([0-9]+)\./);return a?parseInt(a[2],10):!1}var d=Fa(8),g={handle:d,attributes:b,version:b.za,xa:a};g.Aa=2<=g.version&&(!1===c()||58<=c());a.canvas&&(a.canvas.Ka=g);Ma[d]=g;("undefined"===typeof b.ya||b.ya)&&Pa(g);return d}
function Pa(a){a||(a=T);if(!a.Ia){a.Ia=!0;var b=a.xa;if(2>a.version){var c=b.getExtension("ANGLE_instanced_arrays");c&&(b.vertexAttribDivisor=function(a,b){c.vertexAttribDivisorANGLE(a,b)},b.drawArraysInstanced=function(a,b,d,g){c.drawArraysInstancedANGLE(a,b,d,g)},b.drawElementsInstanced=function(a,b,d,g,l){c.drawElementsInstancedANGLE(a,b,d,g,l)});var d=b.getExtension("OES_vertex_array_object");d&&(b.createVertexArray=function(){return d.createVertexArrayOES()},b.deleteVertexArray=function(a){d.deleteVertexArrayOES(a)},
b.bindVertexArray=function(a){d.bindVertexArrayOES(a)},b.isVertexArray=function(a){return d.isVertexArrayOES(a)});var g=b.getExtension("WEBGL_draw_buffers");g&&(b.drawBuffers=function(a,b){g.drawBuffersWEBGL(a,b)})}b.Pa=b.getExtension("EXT_disjoint_timer_query");var l="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic EXT_frag_depth WEBGL_draw_buffers ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear EXT_blend_minmax EXT_shader_texture_lod WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_sRGB WEBGL_compressed_texture_etc1 EXT_disjoint_timer_query WEBGL_compressed_texture_etc WEBGL_compressed_texture_astc EXT_color_buffer_float WEBGL_compressed_texture_s3tc_srgb EXT_disjoint_timer_query_webgl2".split(" ");
(a=b.getSupportedExtensions())&&0<a.length&&b.getSupportedExtensions().forEach(function(a){-1!=l.indexOf(a)&&b.getExtension(a)})}}var Qa={},Ra=["default","low-power","high-performance"];
function Sa(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=Y.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>T.version){W(1282);return}c=2*Y.getSupportedExtensions().length;break;case 33307:case 33308:if(2>T.version){W(1280);return}c=33307==a?3:0}if(void 0===c)switch(d=Y.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":W(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 35097:case 36389:case 34068:c=
0;break;default:W(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)D[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(g){W(1280);w("GL_INVALID_ENUM in glGetIntegerv: Unknown object returned from WebGL getParameter("+a+")! (error: "+g+")");return}}break;default:W(1280);return}D[b>>2]=c}else W(1281)}function Z(a){var b=ea(a)+1,c=Fa(b);C(a,B,c,b);return c}for(var Y,Ta=0;256>Ta;Ta++);
var Va=e.asm({},{H:u,G:function(a){e.___errno_location&&(D[e.___errno_location()>>2]=a);return a},y:function(a,b,c){a=a?O(a):e.canvas;if(!a)return-4;a.getBoundingClientRect?(a=a.getBoundingClientRect(),E[b>>3]=a.right-a.left,E[c>>3]=a.bottom-a.top):(E[b>>3]=a.clientWidth,E[c>>3]=a.clientHeight);return 0},aa:function(){return F},r:function(a,b){function c(d){Ua(a,d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},O:function(a){Da(a)},m:function(a,b,c){"number"===typeof a&&(a=A(a));a=a&&
"#canvas"!==a?"undefined"!==typeof Qa&&U[a]?U[a]:O(a):"undefined"!==typeof Qa&&U.canvas?U.canvas:e.canvas;if(!a)return-4;a.width=b;a.height=c;return 0},I:function(a,b,c,d){Ea(a,b,c,d);return 0},l:function(a,b){var c={};b>>=2;c.alpha=!!D[b];c.depth=!!D[b+1];c.stencil=!!D[b+2];c.antialias=!!D[b+3];c.premultipliedAlpha=!!D[b+4];c.preserveDrawingBuffer=!!D[b+5];c.powerPreference=Ra[D[b+6]];c.failIfMajorPerformanceCaveat=!!D[b+7];c.za=D[b+8];c.Ra=D[b+9];c.ya=D[b+10];c.Ga=D[b+11];c.Sa=D[b+12];c.Ta=D[b+
13];a=(a=A(a))&&"#canvas"!==a||!e.canvas?U[a]?U[a].Ja:O(a):e.canvas.id&&U[e.canvas.id]?U[e.canvas.id].Ja||O(e.canvas.id):e.canvas;!a||c.Ga?c=0:c=(a=1<c.za?a.getContext("webgl2",c):a.getContext("webgl",c)||a.getContext("experimental-webgl",c))&&Oa(a,c);return c},la:function(a){a>>=2;for(var b=0;14>b;++b)D[a+b]=0;D[a]=D[a+1]=D[a+3]=D[a+4]=D[a+8]=D[a+10]=1},ka:function(a){T=Ma[a];e.Ma=Y=T&&T.xa;return!a||Y?0:-5},F:function(a){Y.activeTexture(a)},E:function(a,b){Y.attachShader(P[a],R[b])},f:function(a,
b){35051==a?Y.Na=b:35052==a&&(Y.Oa=b);Y.bindBuffer(a,Ja[b])},D:function(a,b){Y.bindFramebuffer(a,Ka[b])},C:function(a,b){Y.bindTexture(a,La[b])},B:function(a,b,c,d){Y.blendColor(a,b,c,d)},A:function(a,b){Y.blendEquationSeparate(a,b)},z:function(a,b,c,d){Y.blendFuncSeparate(a,b,c,d)},ja:function(a,b,c,d){T.Aa?c?Y.bufferData(a,B,d,c,b):Y.bufferData(a,b,d):Y.bufferData(a,c?B.subarray(c,c+b):b,d)},ia:function(a,b,c,d){T.Aa?Y.bufferSubData(a,b,B,d,c):Y.bufferSubData(a,b,B.subarray(d,d+c))},ha:function(a){Y.clear(a)},
ga:function(a,b,c,d){Y.clearColor(a,b,c,d)},fa:function(a){Y.clearDepth(a)},ea:function(a){Y.clearStencil(a)},k:function(a,b,c,d){Y.colorMask(!!a,!!b,!!c,!!d)},da:function(a){Y.compileShader(R[a])},ca:function(){var a=X(P),b=Y.createProgram();b.name=a;P[a]=b;return a},ba:function(a){var b=X(R);R[b]=Y.createShader(a);return b},x:function(a){Y.cullFace(a)},$:function(a){if(a){var b=P[a];b?(Y.deleteProgram(b),b.name=0,P[a]=null,V[a]=null):W(1281)}},j:function(a){if(a){var b=R[a];b?(Y.deleteShader(b),
R[a]=null):W(1281)}},i:function(a){Y.depthFunc(a)},h:function(a){Y.depthMask(!!a)},c:function(a){Y.disable(a)},b:function(a){Y.disableVertexAttribArray(a)},_:function(a,b,c){Y.drawArrays(a,b,c)},Z:function(a,b,c,d){Y.drawElements(a,b,c,d)},d:function(a){Y.enable(a)},Y:function(a){Y.enableVertexAttribArray(a)},w:function(a){Y.frontFace(a)},X:function(a,b){for(var c=0;c<a;c++){var d=Y.createBuffer(),g=d&&X(Ja);d?(d.name=g,Ja[g]=d):W(1282);D[b+4*c>>2]=g}},v:function(a,b){return Y.getAttribLocation(P[a],
A(b))},u:function(a,b){Sa(a,b)},W:function(a,b,c,d){a=Y.getProgramInfoLog(P[a]);null===a&&(a="(unknown error)");0<b&&d?(b=C(a,B,d,b),c&&(D[c>>2]=b)):c&&(D[c>>2]=0)},t:function(a,b,c){if(c)if(a>=Ha)W(1281);else{var d=V[a];if(d)if(35716==b)a=Y.getProgramInfoLog(P[a]),null===a&&(a="(unknown error)"),D[c>>2]=a.length+1;else if(35719==b)D[c>>2]=d.wa;else if(35722==b){if(-1==d.sa){a=P[a];var g=Y.getProgramParameter(a,35721);for(b=d.sa=0;b<g;++b)d.sa=Math.max(d.sa,Y.getActiveAttrib(a,b).name.length+1)}D[c>>
2]=d.sa}else if(35381==b){if(-1==d.ta)for(a=P[a],g=Y.getProgramParameter(a,35382),b=d.ta=0;b<g;++b)d.ta=Math.max(d.ta,Y.getActiveUniformBlockName(a,b).length+1);D[c>>2]=d.ta}else D[c>>2]=Y.getProgramParameter(P[a],b);else W(1282)}else W(1281)},V:function(a,b,c,d){a=Y.getShaderInfoLog(R[a]);null===a&&(a="(unknown error)");0<b&&d?(b=C(a,B,d,b),c&&(D[c>>2]=b)):c&&(D[c>>2]=0)},s:function(a,b,c){c?35716==b?(a=Y.getShaderInfoLog(R[a]),null===a&&(a="(unknown error)"),D[c>>2]=a.length+1):35720==b?(a=Y.getShaderSource(R[a]),
D[c>>2]=null===a||0==a.length?0:a.length+1):D[c>>2]=Y.getShaderParameter(R[a],b):W(1281)},U:function(a){if(Na[a])return Na[a];switch(a){case 7939:var b=Y.getSupportedExtensions();for(var c=[],d=0;d<b.length;++d)c.push(b[d]),c.push("GL_"+b[d]);b=Z(c.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=Y.getParameter(a))||W(1280);b=Z(b);break;case 7938:b=Y.getParameter(Y.VERSION);b=2<=T.version?"OpenGL ES 3.0 ("+b+")":"OpenGL ES 2.0 ("+b+")";b=Z(b);break;case 35724:b=Y.getParameter(Y.SHADING_LANGUAGE_VERSION);
c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=Z(b);break;default:return W(1280),0}return Na[a]=b},e:function(a,b){b=A(b);var c=0;if("]"==b[b.length-1]){var d=b.lastIndexOf("[");c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=V[a]&&V[a].Ba[b])&&0<=c&&c<a[0]?a[1]+c:-1},T:function(a){Y.linkProgram(P[a]);var b=P[a];a=V[a]={Ba:{},wa:0,sa:-1,ta:-1};for(var c=a.Ba,d=Y.getProgramParameter(b,35718),
g=0;g<d;++g){var l=Y.getActiveUniform(b,g),k=l.name;a.wa=Math.max(a.wa,k.length+1);var x=k.lastIndexOf("[");0<x&&(k=k.slice(0,x));if(x=Y.getUniformLocation(b,k)){var S=X(Q);c[k]=[l.size,S];Q[S]=x;for(var fa=1;fa<l.size;++fa)x=Y.getUniformLocation(b,k+"["+fa+"]"),S=X(Q),Q[S]=x}}},q:function(a,b){Y.polygonOffset(a,b)},S:function(a,b,c,d){Y.scissor(a,b,c,d)},R:function(a,b,c,d){for(var g="",l=0;l<b;++l){var k=d?D[d+4*l>>2]:-1;g+=A(D[c+4*l>>2],0>k?void 0:k)}Y.shaderSource(R[a],g)},Q:function(a,b,c){Y.stencilFunc(a,
b,c)},p:function(a,b,c,d){Y.stencilFuncSeparate(a,b,c,d)},g:function(a){Y.stencilMask(a)},P:function(a,b,c){Y.stencilOp(a,b,c)},o:function(a,b,c,d){Y.stencilOpSeparate(a,b,c,d)},n:function(a,b){Y.uniform1i(Q[a],b)},N:function(a){Y.useProgram(P[a])},M:function(a,b){Y.vertexAttribDivisor(a,b)},L:function(a,b,c,d,g,l){Y.vertexAttribPointer(a,b,c,!!d,g,l)},K:function(a,b,c,d){Y.viewport(a,b,c,d)},J:Da,a:3488},buffer);e.asm=Va;e._free=function(){return e.asm.ma.apply(null,arguments)};
e._main=function(){return e.asm.na.apply(null,arguments)};var Fa=e._malloc=function(){return e.asm.oa.apply(null,arguments)},ia=e.stackAlloc=function(){return e.asm.ra.apply(null,arguments)},Ua=e.dynCall_idi=function(){return e.asm.pa.apply(null,arguments)},Ga=e.dynCall_iiii=function(){return e.asm.qa.apply(null,arguments)};e.asm=Va;function v(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}v.prototype=Error();v.prototype.constructor=v;
K=function Wa(){e.calledRun||Xa();e.calledRun||(K=Wa)};
e.callMain=function(a){a=a||[];H||(H=!0,G(la));var b=a.length+1,c=ia(4*(b+1));D[c>>2]=ha(e.thisProgram);for(var d=1;d<b;d++)D[(c>>2)+d]=ha(a[d-1]);D[(c>>2)+b]=0;try{var g=e._main(b,c,0);if(!e.noExitRuntime||0!==g){if(!e.noExitRuntime&&(z=!0,G(na),e.onExit))e.onExit(g);e.quit(g,new v(g))}}catch(l){l instanceof v||("SimulateInfiniteLoop"==l?e.noExitRuntime=!0:((a=l)&&"object"===typeof l&&l.stack&&(a=[l,l.stack]),w("exception thrown: "+a),e.quit(1,l)))}finally{}};
function Xa(a){function b(){if(!e.calledRun&&(e.calledRun=!0,!z)){H||(H=!0,G(la));G(ma);if(e.onRuntimeInitialized)e.onRuntimeInitialized();e._main&&Ya&&e.callMain(a);if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var b=e.postRun.shift();oa.unshift(b)}G(oa)}}a=a||e.arguments;if(!(0<I)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)pa();G(ka);0<I||e.calledRun||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},
1);b()},1)):b())}}e.run=Xa;function u(a){if(e.onAbort)e.onAbort(a);void 0!==a?(ba(a),w(a),a=JSON.stringify(a)):a="";z=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}e.abort=u;if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();var Ya=!0;e.noInitialRun&&(Ya=!1);e.noExitRuntime=!0;Xa();
