if(typeof process!=="undefined"){var Module={};}var f;f||(f=Module);if("object"===typeof process){var fs=require("fs");f.wasm=fs.readFileSync(__dirname+"/clear-emsc.wasm")}var g="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function k(a){if(a){for(var b=m,c=a+void 0,d=a;b[d]&&!(d>=c);)++d;if(16<d-a&&b.subarray&&g)a=g.decode(b.subarray(a,d));else{for(c="";a<d;){var e=b[a++];if(e&128){var l=b[a++]&63;if(192==(e&224))c+=String.fromCharCode((e&31)<<6|l);else{var h=b[a++]&63;e=224==(e&240)?(e&15)<<12|l<<6|h:(e&7)<<18|l<<12|h<<6|b[a++]&63;65536>e?c+=String.fromCharCode(e):(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}a=c}}else a="";return a}
var n=new WebAssembly.Memory({initial:2048,maximum:2048}),buffer=n.buffer;new Int8Array(buffer);new Int16Array(buffer);var p=new Int32Array(buffer),m=new Uint8Array(buffer);new Uint16Array(buffer);new Uint32Array(buffer);new Float32Array(buffer);var q=new Float64Array(buffer);p[812]=5246384;var r=0;
function t(a){try{if(!a)return window;"number"===typeof a&&(a=k(a));return"#window"===a?window:"#document"===a?document:"#screen"===a?window.screen:"#canvas"===a?f.canvas:"string"===typeof a?document.getElementById(a):a}catch(b){return null}}var u=[];function v(){if(w&&x.T)for(var a=0;a<u.length;++a){var b=u[a];u.splice(a,1);--a;b.ka.apply(this,b.aa)}}var w=0,x=null,y=[];function z(a){var b=y[a];b.target.removeEventListener(b.J,b.V,b.S);y.splice(a,1)}
function A(a){function b(b){++w;x=a;v();a.X(b);v();--w}if(a.U)a.V=b,a.target.addEventListener(a.J,b,a.S),y.push(a);else for(var c=0;c<y.length;++c)y[c].target==a.target&&y[c].J==a.J&&z(c--)}
function B(a,b,c,d){r||(r=C(36));a=t(a);A({target:a,T:!1,J:"resize",U:d,X:function(c){c=c||window.event;if(c.target==a){var e=0<window.pageXOffset||0<window.pageYOffset?[window.pageXOffset,window.pageYOffset]:"undefined"!==typeof document.documentElement.scrollLeft||"undefined"!==typeof document.documentElement.scrollTop?[document.documentElement.scrollLeft,document.documentElement.scrollTop]:[document.body.scrollLeft|0,document.body.scrollTop|0],h=r;p[h>>2]=c.detail;p[h+4>>2]=document.body.clientWidth;
p[h+8>>2]=document.body.clientHeight;p[h+12>>2]=window.innerWidth;p[h+16>>2]=window.innerHeight;p[h+20>>2]=window.outerWidth;p[h+24>>2]=window.outerHeight;p[h+28>>2]=e[0];p[h+32>>2]=e[1];D(d,10,h,b)&&c.preventDefault()}},S:c})}var E=0,F=[],G=[],H={},I=null,J={},K={};function L(a){E||(E=a)}
function M(a,b){function c(){var a=navigator.userAgent.match(/Chrom(e|ium)\/([0-9]+)\./);return a?parseInt(a[2],10):!1}var d=C(8),e={handle:d,attributes:b,version:b.R,M:a};e.ja=2<=e.version&&(!1===c()||58<=c());a.canvas&&(a.canvas.$=e);H[d]=e;("undefined"===typeof b.N||b.N)&&N(e);return d}
function N(a){a||(a=I);if(!a.Y){a.Y=!0;var b=a.M;if(2>a.version){var c=b.getExtension("ANGLE_instanced_arrays");c&&(b.vertexAttribDivisor=function(a,b){c.vertexAttribDivisorANGLE(a,b)},b.drawArraysInstanced=function(a,b,d,e){c.drawArraysInstancedANGLE(a,b,d,e)},b.drawElementsInstanced=function(a,b,d,e,l){c.drawElementsInstancedANGLE(a,b,d,e,l)});var d=b.getExtension("OES_vertex_array_object");d&&(b.createVertexArray=function(){return d.createVertexArrayOES()},b.deleteVertexArray=function(a){d.deleteVertexArrayOES(a)},
b.bindVertexArray=function(a){d.bindVertexArrayOES(a)},b.isVertexArray=function(a){return d.isVertexArrayOES(a)});var e=b.getExtension("WEBGL_draw_buffers");e&&(b.drawBuffers=function(a,b){e.drawBuffersWEBGL(a,b)})}b.fa=b.getExtension("EXT_disjoint_timer_query");var l="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic EXT_frag_depth WEBGL_draw_buffers ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear EXT_blend_minmax EXT_shader_texture_lod WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_sRGB WEBGL_compressed_texture_etc1 EXT_disjoint_timer_query WEBGL_compressed_texture_etc WEBGL_compressed_texture_astc EXT_color_buffer_float WEBGL_compressed_texture_s3tc_srgb EXT_disjoint_timer_query_webgl2".split(" ");
(a=b.getSupportedExtensions())&&0<a.length&&b.getSupportedExtensions().forEach(function(a){-1!=l.indexOf(a)&&b.getExtension(a)})}}var O={},P=["default","low-power","high-performance"];
function Q(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=R.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>I.version){L(1282);return}c=2*R.getSupportedExtensions().length;break;case 33307:case 33308:if(2>I.version){L(1280);return}c=33307==a?3:0}if(void 0===c)switch(d=R.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":L(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 35097:case 36389:case 34068:c=
0;break;default:L(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)p[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){L(1280);console.error("GL_INVALID_ENUM in glGetIntegerv: Unknown object returned from WebGL getParameter("+a+")! (error: "+e+")");return}}break;default:L(1280);return}p[b>>2]=c}else L(1281)}
function S(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}var e=b+1;b=C(e);c=b;d=m;if(0<e){e=c+e-1;for(var l=0;l<a.length;++l){var h=a.charCodeAt(l);if(55296<=h&&57343>=h){var V=a.charCodeAt(++l);h=65536+((h&1023)<<10)|V&1023}if(127>=h){if(c>=e)break;d[c++]=h}else{if(2047>=h){if(c+1>=e)break;d[c++]=192|h>>6}else{if(65535>=h){if(c+2>=e)break;d[c++]=224|h>>12}else{if(c+3>=e)break;
d[c++]=240|h>>18;d[c++]=128|h>>12&63}d[c++]=128|h>>6&63}d[c++]=128|h&63}}d[c]=0}return b}for(var R,T=0;256>T;T++);
var W={p:function(a){throw a;},o:function(a,b,c){a=a?t(a):f.canvas;if(!a)return-4;a.getBoundingClientRect?(a=a.getBoundingClientRect(),q[b>>3]=a.right-a.left,q[c>>3]=a.bottom-a.top):(q[b>>3]=a.clientWidth,q[c>>3]=a.clientHeight);return 0},A:function(){return 134217728},i:function(a,b){function c(d){U(a,d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},g:function(a,b,c){"number"===typeof a&&(a=k(a));a=a&&"#canvas"!==a?"undefined"!==typeof O&&J[a]?J[a]:t(a):"undefined"!==typeof O&&J.canvas?
J.canvas:f.canvas;if(!a)return-4;a.width=b;a.height=c;return 0},s:function(a,b,c,d){B(a,b,c,d);return 0},f:function(a,b){var c={};b>>=2;c.alpha=!!p[b];c.depth=!!p[b+1];c.stencil=!!p[b+2];c.antialias=!!p[b+3];c.premultipliedAlpha=!!p[b+4];c.preserveDrawingBuffer=!!p[b+5];c.powerPreference=P[p[b+6]];c.failIfMajorPerformanceCaveat=!!p[b+7];c.R=p[b+8];c.ga=p[b+9];c.N=p[b+10];c.W=p[b+11];c.ha=p[b+12];c.ia=p[b+13];a=(a=k(a))&&"#canvas"!==a||!f.canvas?J[a]?J[a].Z:t(a):f.canvas.id&&J[f.canvas.id]?J[f.canvas.id].Z||
t(f.canvas.id):f.canvas;!a||c.W?c=0:c=(a=1<c.R?a.getContext("webgl2",c):a.getContext("webgl",c)||a.getContext("experimental-webgl",c))&&M(a,c);return c},r:function(a){a>>=2;for(var b=0;14>b;++b)p[a+b]=0;p[a]=p[a+1]=p[a+3]=p[a+4]=p[a+8]=p[a+10]=1},q:function(a){I=H[a];f.ba=R=I&&I.M;return!a||R?0:-5},e:function(a,b){35051==a?R.da=b:35052==a&&(R.ea=b);R.bindBuffer(a,F[b])},n:function(a,b){R.bindFramebuffer(a,G[b])},I:function(a,b,c,d){R.blendColor(a,b,c,d)},H:function(a,b){R.blendEquationSeparate(a,
b)},G:function(a,b,c,d){R.blendFuncSeparate(a,b,c,d)},F:function(a){R.clear(a)},E:function(a,b,c,d){R.clearColor(a,b,c,d)},D:function(a){R.clearDepth(a)},C:function(a){R.clearStencil(a)},m:function(a,b,c,d){R.colorMask(!!a,!!b,!!c,!!d)},B:function(a){R.cullFace(a)},l:function(a){R.depthFunc(a)},k:function(a){R.depthMask(!!a)},c:function(a){R.disable(a)},b:function(a){R.disableVertexAttribArray(a)},d:function(a){R.enable(a)},z:function(a){R.frontFace(a)},j:function(a,b){Q(a,b)},y:function(a){if(K[a])return K[a];
switch(a){case 7939:var b=R.getSupportedExtensions();for(var c=[],d=0;d<b.length;++d)c.push(b[d]),c.push("GL_"+b[d]);b=S(c.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=R.getParameter(a))||L(1280);b=S(b);break;case 7938:b=R.getParameter(R.VERSION);b=2<=I.version?"OpenGL ES 3.0 ("+b+")":"OpenGL ES 2.0 ("+b+")";b=S(b);break;case 35724:b=R.getParameter(R.SHADING_LANGUAGE_VERSION);c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+
c[1]+" ("+b+")");b=S(b);break;default:return L(1280),0}return K[a]=b},x:function(a,b){R.polygonOffset(a,b)},w:function(a,b,c,d){R.scissor(a,b,c,d)},v:function(a,b,c){R.stencilFunc(a,b,c)},h:function(a){R.stencilMask(a)},u:function(a,b,c){R.stencilOp(a,b,c)},t:function(a,b,c,d){R.viewport(a,b,c,d)},a:3248};W.memory=n;W.table=new WebAssembly.Table({initial:4,maximum:4,element:"anyfunc"});W.__memory_base=1024;W.__table_base=0;var X,C,U,D;
WebAssembly.instantiate(f.wasm,{env:W,global:{NaN:NaN,Infinity:Infinity},"global.Math":Math,asm2wasm:{"f64-rem":function(a,b){return a%b},"debugger":function(){debugger}}}).then(function(a){a=a.instance.exports;X=a.K;C=a.L;U=a.O;D=a.P;X()});
