if(typeof process!=="undefined"){var Module={};}var e;e||(e=Module);if("object"===typeof process){var fs=require("fs");e.wasm=fs.readFileSync(__dirname+"/triangle-emsc.wasm")}var g="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function l(a,b){if(a){var c=m,d=a+b;for(b=a;c[b]&&!(b>=d);)++b;if(16<b-a&&c.subarray&&g)a=g.decode(c.subarray(a,b));else{for(d="";a<b;){var f=c[a++];if(f&128){var k=c[a++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|k);else{var h=c[a++]&63;f=224==(f&240)?(f&15)<<12|k<<6|h:(f&7)<<18|k<<12|h<<6|c[a++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}a=d}}else a="";return a}
function n(a,b,c){var d=m;if(!(0<c))return 0;var f=b;c=b+c-1;for(var k=0;k<a.length;++k){var h=a.charCodeAt(k);if(55296<=h&&57343>=h){var r=a.charCodeAt(++k);h=65536+((h&1023)<<10)|r&1023}if(127>=h){if(b>=c)break;d[b++]=h}else{if(2047>=h){if(b+1>=c)break;d[b++]=192|h>>6}else{if(65535>=h){if(b+2>=c)break;d[b++]=224|h>>12}else{if(b+3>=c)break;d[b++]=240|h>>18;d[b++]=128|h>>12&63}d[b++]=128|h>>6&63}d[b++]=128|h&63}}d[b]=0;return b-f}var p=new WebAssembly.Memory({initial:2048,maximum:2048}),buffer=p.buffer;
new Int8Array(buffer);new Int16Array(buffer);var q=new Int32Array(buffer),m=new Uint8Array(buffer);new Uint16Array(buffer);new Uint32Array(buffer);new Float32Array(buffer);var t=new Float64Array(buffer);q[872]=5246624;var u=0;function v(a){try{if(!a)return window;"number"===typeof a&&(a=l(a));return"#window"===a?window:"#document"===a?document:"#screen"===a?window.screen:"#canvas"===a?e.canvas:"string"===typeof a?document.getElementById(a):a}catch(b){return null}}var w=[];
function x(){if(y&&z.xa)for(var a=0;a<w.length;++a){var b=w[a];w.splice(a,1);--a;b.Na.apply(this,b.Fa)}}var y=0,z=null,A=[];function B(a){var b=A[a];b.target.removeEventListener(b.na,b.za,b.wa);A.splice(a,1)}function aa(a){function b(b){++y;z=a;x();a.Ba(b);x();--y}if(a.ya)a.za=b,a.target.addEventListener(a.na,b,a.wa),A.push(a);else for(var c=0;c<A.length;++c)A[c].target==a.target&&A[c].na==a.na&&B(c--)}
function ba(a,b,c,d){u||(u=C(36));a=v(a);aa({target:a,xa:!1,na:"resize",ya:d,Ba:function(c){c=c||window.event;if(c.target==a){var f=0<window.pageXOffset||0<window.pageYOffset?[window.pageXOffset,window.pageYOffset]:"undefined"!==typeof document.documentElement.scrollLeft||"undefined"!==typeof document.documentElement.scrollTop?[document.documentElement.scrollLeft,document.documentElement.scrollTop]:[document.body.scrollLeft|0,document.body.scrollTop|0],h=u;q[h>>2]=c.detail;q[h+4>>2]=document.body.clientWidth;
q[h+8>>2]=document.body.clientHeight;q[h+12>>2]=window.innerWidth;q[h+16>>2]=window.innerHeight;q[h+20>>2]=window.outerWidth;q[h+24>>2]=window.outerHeight;q[h+28>>2]=f[0];q[h+32>>2]=f[1];D(d,10,h,b)&&c.preventDefault()}},wa:c})}var F=1,G=0,H=[],I=[],ca=[],da=[],J=[],K=[],L={},N=null,O={},P={},Q={};function R(a){G||(G=a)}function S(a){for(var b=F++,c=a.length;c<b;c++)a[c]=null;return b}
function ea(a,b){function c(){var a=navigator.userAgent.match(/Chrom(e|ium)\/([0-9]+)\./);return a?parseInt(a[2],10):!1}var d=C(8),f={handle:d,attributes:b,version:b.ta,ra:a};f.ua=2<=f.version&&(!1===c()||58<=c());a.canvas&&(a.canvas.Ea=f);L[d]=f;("undefined"===typeof b.sa||b.sa)&&fa(f);return d}
function fa(a){a||(a=N);if(!a.Ca){a.Ca=!0;var b=a.ra;if(2>a.version){var c=b.getExtension("ANGLE_instanced_arrays");c&&(b.vertexAttribDivisor=function(a,b){c.vertexAttribDivisorANGLE(a,b)},b.drawArraysInstanced=function(a,b,d,f){c.drawArraysInstancedANGLE(a,b,d,f)},b.drawElementsInstanced=function(a,b,d,f,k){c.drawElementsInstancedANGLE(a,b,d,f,k)});var d=b.getExtension("OES_vertex_array_object");d&&(b.createVertexArray=function(){return d.createVertexArrayOES()},b.deleteVertexArray=function(a){d.deleteVertexArrayOES(a)},
b.bindVertexArray=function(a){d.bindVertexArrayOES(a)},b.isVertexArray=function(a){return d.isVertexArrayOES(a)});var f=b.getExtension("WEBGL_draw_buffers");f&&(b.drawBuffers=function(a,b){f.drawBuffersWEBGL(a,b)})}b.Ja=b.getExtension("EXT_disjoint_timer_query");var k="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic EXT_frag_depth WEBGL_draw_buffers ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear EXT_blend_minmax EXT_shader_texture_lod WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_sRGB WEBGL_compressed_texture_etc1 EXT_disjoint_timer_query WEBGL_compressed_texture_etc WEBGL_compressed_texture_astc EXT_color_buffer_float WEBGL_compressed_texture_s3tc_srgb EXT_disjoint_timer_query_webgl2".split(" ");
(a=b.getSupportedExtensions())&&0<a.length&&b.getSupportedExtensions().forEach(function(a){-1!=k.indexOf(a)&&b.getExtension(a)})}}var T={},ha=["default","low-power","high-performance"];
function ia(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=U.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>N.version){R(1282);return}c=2*U.getSupportedExtensions().length;break;case 33307:case 33308:if(2>N.version){R(1280);return}c=33307==a?3:0}if(void 0===c)switch(d=U.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":R(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 35097:case 36389:case 34068:c=
0;break;default:R(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)q[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(f){R(1280);console.error("GL_INVALID_ENUM in glGetIntegerv: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:R(1280);return}q[b>>2]=c}else R(1281)}
function V(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}b+=1;c=C(b);n(a,c,b);return c}for(var U,W=0;256>W;W++);
var Y={G:function(a){throw a;},F:function(a,b,c){a=a?v(a):e.canvas;if(!a)return-4;a.getBoundingClientRect?(a=a.getBoundingClientRect(),t[b>>3]=a.right-a.left,t[c>>3]=a.bottom-a.top):(t[b>>3]=a.clientWidth,t[c>>3]=a.clientHeight);return 0},fa:function(){return 134217728},x:function(a,b){function c(d){X(a,d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},v:function(a,b,c){"number"===typeof a&&(a=l(a));a=a&&"#canvas"!==a?"undefined"!==typeof T&&O[a]?O[a]:v(a):"undefined"!==typeof T&&O.canvas?
O.canvas:e.canvas;if(!a)return-4;a.width=b;a.height=c;return 0},R:function(a,b,c,d){ba(a,b,c,d);return 0},m:function(a,b){var c={};b>>=2;c.alpha=!!q[b];c.depth=!!q[b+1];c.stencil=!!q[b+2];c.antialias=!!q[b+3];c.premultipliedAlpha=!!q[b+4];c.preserveDrawingBuffer=!!q[b+5];c.powerPreference=ha[q[b+6]];c.failIfMajorPerformanceCaveat=!!q[b+7];c.ta=q[b+8];c.Ka=q[b+9];c.sa=q[b+10];c.Aa=q[b+11];c.La=q[b+12];c.Ma=q[b+13];a=(a=l(a))&&"#canvas"!==a||!e.canvas?O[a]?O[a].Da:v(a):e.canvas.id&&O[e.canvas.id]?O[e.canvas.id].Da||
v(e.canvas.id):e.canvas;!a||c.Aa?c=0:c=(a=1<c.ta?a.getContext("webgl2",c):a.getContext("webgl",c)||a.getContext("experimental-webgl",c))&&ea(a,c);return c},I:function(a){a>>=2;for(var b=0;14>b;++b)q[a+b]=0;q[a]=q[a+1]=q[a+3]=q[a+4]=q[a+8]=q[a+10]=1},H:function(a){N=L[a];e.Ga=U=N&&N.ra;return!a||U?0:-5},l:function(a){U.activeTexture(a)},E:function(a,b){U.attachShader(I[a],K[b])},f:function(a,b){35051==a?U.Ha=b:35052==a&&(U.Ia=b);U.bindBuffer(a,H[b])},D:function(a,b){U.bindFramebuffer(a,ca[b])},C:function(a,
b){U.bindTexture(a,da[b])},B:function(a,b,c,d){U.blendColor(a,b,c,d)},A:function(a,b){U.blendEquationSeparate(a,b)},z:function(a,b,c,d){U.blendFuncSeparate(a,b,c,d)},ia:function(a,b,c,d){N.ua?c?U.bufferData(a,m,d,c,b):U.bufferData(a,b,d):U.bufferData(a,c?m.subarray(c,c+b):b,d)},ha:function(a,b,c,d){N.ua?U.bufferSubData(a,b,m,d,c):U.bufferSubData(a,b,m.subarray(d,d+c))},ga:function(a){U.clear(a)},ea:function(a,b,c,d){U.clearColor(a,b,c,d)},da:function(a){U.clearDepth(a)},ca:function(a){U.clearStencil(a)},
k:function(a,b,c,d){U.colorMask(!!a,!!b,!!c,!!d)},ba:function(a){U.compileShader(K[a])},aa:function(){var a=S(I),b=U.createProgram();b.name=a;I[a]=b;return a},$:function(a){var b=S(K);K[b]=U.createShader(a);return b},y:function(a){U.cullFace(a)},_:function(a){if(a){var b=I[a];b?(U.deleteProgram(b),b.name=0,I[a]=null,P[a]=null):R(1281)}},j:function(a){if(a){var b=K[a];b?(U.deleteShader(b),K[a]=null):R(1281)}},i:function(a){U.depthFunc(a)},h:function(a){U.depthMask(!!a)},c:function(a){U.disable(a)},
b:function(a){U.disableVertexAttribArray(a)},Z:function(a,b,c){U.drawArrays(a,b,c)},Y:function(a,b,c,d){U.drawElements(a,b,c,d)},d:function(a){U.enable(a)},X:function(a){U.enableVertexAttribArray(a)},w:function(a){U.frontFace(a)},W:function(a,b){for(var c=0;c<a;c++){var d=U.createBuffer(),f=d&&S(H);d?(d.name=f,H[f]=d):R(1282);q[b+4*c>>2]=f}},u:function(a,b){return U.getAttribLocation(I[a],l(b))},t:function(a,b){ia(a,b)},V:function(a,b,c,d){a=U.getProgramInfoLog(I[a]);null===a&&(a="(unknown error)");
0<b&&d?(b=n(a,d,b),c&&(q[c>>2]=b)):c&&(q[c>>2]=0)},s:function(a,b,c){if(c)if(a>=F)R(1281);else{var d=P[a];if(d)if(35716==b)a=U.getProgramInfoLog(I[a]),null===a&&(a="(unknown error)"),q[c>>2]=a.length+1;else if(35719==b)q[c>>2]=d.qa;else if(35722==b){if(-1==d.ja){a=I[a];var f=U.getProgramParameter(a,35721);for(b=d.ja=0;b<f;++b)d.ja=Math.max(d.ja,U.getActiveAttrib(a,b).name.length+1)}q[c>>2]=d.ja}else if(35381==b){if(-1==d.ma)for(a=I[a],f=U.getProgramParameter(a,35382),b=d.ma=0;b<f;++b)d.ma=Math.max(d.ma,
U.getActiveUniformBlockName(a,b).length+1);q[c>>2]=d.ma}else q[c>>2]=U.getProgramParameter(I[a],b);else R(1282)}else R(1281)},U:function(a,b,c,d){a=U.getShaderInfoLog(K[a]);null===a&&(a="(unknown error)");0<b&&d?(b=n(a,d,b),c&&(q[c>>2]=b)):c&&(q[c>>2]=0)},r:function(a,b,c){c?35716==b?(a=U.getShaderInfoLog(K[a]),null===a&&(a="(unknown error)"),q[c>>2]=a.length+1):35720==b?(a=U.getShaderSource(K[a]),q[c>>2]=null===a||0==a.length?0:a.length+1):q[c>>2]=U.getShaderParameter(K[a],b):R(1281)},T:function(a){if(Q[a])return Q[a];
switch(a){case 7939:var b=U.getSupportedExtensions();for(var c=[],d=0;d<b.length;++d)c.push(b[d]),c.push("GL_"+b[d]);b=V(c.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=U.getParameter(a))||R(1280);b=V(b);break;case 7938:b=U.getParameter(U.VERSION);b=2<=N.version?"OpenGL ES 3.0 ("+b+")":"OpenGL ES 2.0 ("+b+")";b=V(b);break;case 35724:b=U.getParameter(U.SHADING_LANGUAGE_VERSION);c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+
c[1]+" ("+b+")");b=V(b);break;default:return R(1280),0}return Q[a]=b},e:function(a,b){b=l(b);var c=0;if("]"==b[b.length-1]){var d=b.lastIndexOf("[");c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=P[a]&&P[a].va[b])&&0<=c&&c<a[0]?a[1]+c:-1},S:function(a){U.linkProgram(I[a]);var b=I[a];a=P[a]={va:{},qa:0,ja:-1,ma:-1};for(var c=a.va,d=U.getProgramParameter(b,35718),f=0;f<d;++f){var k=U.getActiveUniform(b,f),h=k.name;a.qa=Math.max(a.qa,h.length+1);var r=h.lastIndexOf("[");0<r&&(h=h.slice(0,
r));if(r=U.getUniformLocation(b,h)){var E=S(J);c[h]=[k.size,E];J[E]=r;for(var M=1;M<k.size;++M)r=U.getUniformLocation(b,h+"["+M+"]"),E=S(J),J[E]=r}}},q:function(a,b){U.polygonOffset(a,b)},Q:function(a,b,c,d){U.scissor(a,b,c,d)},P:function(a,b,c,d){for(var f="",k=0;k<b;++k){var h=d?q[d+4*k>>2]:-1;f+=l(q[c+4*k>>2],0>h?void 0:h)}U.shaderSource(K[a],f)},O:function(a,b,c){U.stencilFunc(a,b,c)},p:function(a,b,c,d){U.stencilFuncSeparate(a,b,c,d)},g:function(a){U.stencilMask(a)},N:function(a,b,c){U.stencilOp(a,
b,c)},o:function(a,b,c,d){U.stencilOpSeparate(a,b,c,d)},n:function(a,b){U.uniform1i(J[a],b)},M:function(a){U.useProgram(I[a])},L:function(a,b){U.vertexAttribDivisor(a,b)},K:function(a,b,c,d,f,k){U.vertexAttribPointer(a,b,c,!!d,f,k)},J:function(a,b,c,d){U.viewport(a,b,c,d)},a:3488};Y.memory=p;Y.table=new WebAssembly.Table({initial:4,maximum:4,element:"anyfunc"});Y.__memory_base=1024;Y.__table_base=0;var Z,C,X,D;
WebAssembly.instantiate(e.wasm,{env:Y,global:{NaN:NaN,Infinity:Infinity},"global.Math":Math,asm2wasm:{"f64-rem":function(a,b){return a%b},"debugger":function(){debugger}}}).then(function(a){a=a.instance.exports;Z=a.ka;C=a.la;X=a.oa;D=a.pa;Z()});
